import { LiveStore, NamedNode, Node, st, literal, sym } from 'rdflib'
import { ns } from 'solid-ui'
import { ResumeRow } from './types'
import { MutationOps } from '../shared/types'
import { applyUpdaterPatch, collectLinkedNodeStatements, collectNodeStatements, findExistingNode, replacePredicateStatements } from '../shared/rdfMutationHelpers'
import { createIdNode } from '../shared/idNodeFactory'
import { mutationSaveResumeFailedPrefixText, resumeUpdateEntryNotFoundErrorMessageText } from '../../texts'

function asXsdDateLiteral(dateLike: { value?: string } | null | undefined) {
  const value = (dateLike?.value || '').trim()
  if (!value) return null

  const dateOnly = value.slice(0, 10)
  return literal(dateOnly, ns.xsd('date'))
}

/* The following helper was generated by AI Model: GPT-5.3-Codex. */
/* Prompt: write me a function to determine PastRole, CurrentRole, or FutureRole based on resume role date data. 
           The function should return a NamedNode with the correct solid namespace and role type local name. 
           The function should use the roleType field if it is set to one of those three values, 
           otherwise it should infer the role type based on the start and end dates and isCurrentRole field. */
function membershipTypeForRole(resumeData: ResumeRow): NamedNode {
  const normalizedRoleType = (resumeData.roleType || '').trim()
  if (normalizedRoleType === 'PastRole' || normalizedRoleType === 'CurrentRole' || normalizedRoleType === 'FutureRole') {
    return ns.solid(normalizedRoleType)
  }

  if (resumeData.isCurrentRole) return ns.solid('CurrentRole')

  const todayIso = new Date().toISOString().slice(0, 10)
  const startIso = resumeData.startDate?.value?.slice(0, 10) || ''
  const endIso = resumeData.endDate?.value?.slice(0, 10) || ''

  if (startIso && startIso > todayIso) return ns.solid('FutureRole')
  if (endIso && endIso < todayIso) return ns.solid('PastRole')
  return ns.solid('FutureRole')
}

function roleTypeNode(orgType: string): NamedNode | null {
  const text = (orgType || '').trim()
  if (!text) return null

  // These are membership role classes, not organization classes.
  if (text === 'PastRole' || text === 'CurrentRole' || text === 'FutureRole') {
    return null
  }

  if (text.startsWith('http://') || text.startsWith('https://')) {
    const local = text.split(/[#/]/).pop()
    if (local === 'PastRole' || local === 'CurrentRole' || local === 'FutureRole') {
      return null
    }
    return sym(text)
  }

  const prefixed = text.match(/^([a-zA-Z][\w-]*):(.*)$/)
  if (prefixed) {
    const prefix = prefixed[1].toLowerCase()
    const local = prefixed[2].trim()
    if (!local) return null
    if (local === 'PastRole' || local === 'CurrentRole' || local === 'FutureRole') {
      return null
    }
    /* Organization types vary need to return the correct namespace */
    if (prefix === 'schema') return ns.schema(local)
    if (prefix === 'vcard') return ns.vcard(local)
    if (prefix === 'solid') return ns.solid(local)
    if (prefix === 'org') return ns.org(local)
    return null
  }

  // For plain values like "Corporation", map to schema:Corporation.
  return ns.schema(text)
}

/* The following helper was generated by AI Model: GPT-5.3-Codex.
   Prompt: 'do you see anything I can do differently in the mutation code so that it's not so verbose and possible reusable accross sections' */
function buildOrganizationStatements(doc: NamedNode, membershipNode: Node, resumeData: ResumeRow) {
  if (!resumeData.orgName && !resumeData.orgType && !resumeData.orgLocation && !resumeData.orgHomePage) {
    return []
  }

  const organizationNode = createIdNode(doc)
  const inserts: any[] = [
    st(membershipNode as any, ns.org('organization'), organizationNode, doc)
  ]

  const organizationClassNode = roleTypeNode(resumeData.orgType || '')
  if (organizationClassNode) {
    inserts.push(st(organizationNode, ns.rdf('type'), organizationClassNode, doc))
  }

  inserts.push(st(organizationNode, ns.rdf('type'), ns.vcard('Organization'), doc))

  if (resumeData.orgName) {
    inserts.push(st(organizationNode, ns.schema('name'), literal(resumeData.orgName), doc))
  }
  if (resumeData.orgLocation) {
    inserts.push(st(organizationNode, ns.org('location'), literal(resumeData.orgLocation), doc))
  }
  if (resumeData.orgHomePage) {
    inserts.push(st(organizationNode, ns.schema('uri'), literal(resumeData.orgHomePage), doc))
  }

  return inserts
}


function buildResumeStatements(
  subject: NamedNode,
  doc: NamedNode,
  node: Node,
  resumeData: ResumeRow,
  includeMembershipLink = true
) {
  const inserts: any[] = []

  if (includeMembershipLink) {
    inserts.push(st(node as any, ns.org('member'), subject, doc))
  }

  inserts.push(st(node as any, ns.rdf('type'), membershipTypeForRole(resumeData), doc))

  if (resumeData.title) {
    inserts.push(st(node as any, ns.vcard('role'), literal(resumeData.title), doc))
  }
  if (resumeData.startDate) {
    const startDateLiteral = asXsdDateLiteral(resumeData.startDate as any)
    if (startDateLiteral) {
      inserts.push(st(node as any, ns.schema('startDate'), startDateLiteral as any, doc))
    }
  }
  if (resumeData.endDate && !resumeData.isCurrentRole) {
    const endDateLiteral = asXsdDateLiteral(resumeData.endDate as any)
    if (endDateLiteral) {
      inserts.push(st(node as any, ns.schema('endDate'), endDateLiteral as any, doc))
    }
  }
  if (resumeData.description) {
    inserts.push(st(node as any, ns.schema('description'), literal(resumeData.description), doc))
  }

  inserts.push(...buildOrganizationStatements(doc, node, resumeData))

  return inserts
}

async function mutateResumeEntries(store: LiveStore, subject: NamedNode, resumeOps: MutationOps<ResumeRow>) {
  const doc = subject.doc()
  const existingResumeNodes = store.each(null, ns.org('member'), subject, doc) as Node[]
  const deletions: any[] = []
  const insertions: any[] = []

  resumeOps.remove.forEach((resume) => {
    if (!resume.entryNode) return
    const existingNode = findExistingNode(existingResumeNodes, resume.entryNode)
    if (existingNode) {
      const linkedOrganizations = collectLinkedNodeStatements(store, existingNode, ns.org('organization'), doc)
      deletions.push(...linkedOrganizations.linkedStatements)
      deletions.push(...collectNodeStatements(store, existingNode, doc))
    }
  })

  resumeOps.update.forEach((resume) => {
    if (!resume.entryNode) return
    const existingNode = findExistingNode(existingResumeNodes, resume.entryNode)
    if (!existingNode) {
      throw new Error(resumeUpdateEntryNotFoundErrorMessageText)
    }

    if ((existingNode as any).termType === 'BlankNode') {
      // Blank node labels are not always stable for remote updates; migrate to a named node.
      const migratedNode = createIdNode(doc)
      insertions.push(...buildResumeStatements(subject, doc, migratedNode, resume, true))
      return
    }

    // For updates on existing named memberships, keep the membership link and replace only mutable fields.
    ;[ns.rdf('type'), ns.vcard('role'), ns.schema('startDate'), ns.schema('endDate'), ns.schema('description')]
      .forEach((predicate) => {
        replacePredicateStatements(store, existingNode as NamedNode, predicate, doc, deletions, insertions, null)
      })

    const linkedOrganizations = collectLinkedNodeStatements(store, existingNode, ns.org('organization'), doc)
    deletions.push(...linkedOrganizations.linkedStatements)
    deletions.push(...linkedOrganizations.linkStatements)

    insertions.push(...buildResumeStatements(subject, doc, existingNode, resume, false))
  })

  resumeOps.create.forEach((resume) => {
    insertions.push(...buildResumeStatements(subject, doc, createIdNode(doc), resume))
  })

  await applyUpdaterPatch(store, deletions, insertions)
}

export type ResumeMutationPlan = MutationOps<ResumeRow>

export async function processResumeMutations(store: LiveStore, subject: NamedNode, mutationPlan: ResumeMutationPlan) {
  try {
    await mutateResumeEntries(store, subject, mutationPlan)

  } catch (error) {
    const message = error instanceof Error ? error.message : String(error)
    throw new Error(`${mutationSaveResumeFailedPrefixText} ${message}`)
  }
} 
