import { html } from 'lit-html'
import { RoleDetails } from './types'
import { ViewerMode } from '../../types'
import '../../styles/CVCard.css'
import { resumeHeadingText } from '../../texts'
import { Literal, LiveStore, NamedNode } from 'rdflib'
import { createResumeEditDialog } from './ResumeEditDialog'

let descriptionResizeBound = false

/* Function below generated by AI Model: GPT-5.3-Codex */
/* Prompt: the description needs to only show 2 lines and then more button
   please generate code for this. */
function updateDescriptionOverflow(root: ParentNode = document) {
  const wraps = root.querySelectorAll('.cvDescriptionWrap')
  wraps.forEach((wrap) => {
    const textEl = wrap.querySelector('.cvDescriptionText') as HTMLElement | null
    const button = wrap.querySelector('.cvDescriptionToggle') as HTMLButtonElement | null
    if (!textEl || !button) return

    const isExpanded = textEl.classList.contains('isExpanded')
    if (isExpanded) {
      button.hidden = false
      return
    }

    const isOverflowing = textEl.scrollHeight > textEl.clientHeight + 1
    button.hidden = !isOverflowing
    if (!isOverflowing) {
      button.setAttribute('aria-expanded', 'false')
      button.textContent = '...more'
    }
  })
}

function scheduleDescriptionOverflowCheck() {
  if (typeof window === 'undefined') return
  window.requestAnimationFrame(() => updateDescriptionOverflow(window.document))

  if (!descriptionResizeBound) {
    window.addEventListener('resize', () => scheduleDescriptionOverflowCheck())
    descriptionResizeBound = true
  }
}

function toggleDescription(event: Event) {
  const button = event.currentTarget as HTMLButtonElement | null
  if (!button) return

  const descriptionId = button.getAttribute('aria-controls')
  if (!descriptionId) return

  const textEl = document.getElementById(descriptionId)
  if (!textEl) return

  const isExpanded = textEl.classList.toggle('isExpanded')
  button.setAttribute('aria-expanded', isExpanded ? 'true' : 'false')
  button.textContent = isExpanded ? '...less' : '...more'
  if (!isExpanded) {
    scheduleDescriptionOverflowCheck()
  }
}

/* Function below generated by AI Model: GPT-5.3-Codex */
/* Prompt: write me a function to convert a date to Month, Year */
function formatMonthYear(date?: Literal): string {
  if (!date?.value) return ''

  const year = date.value.slice(0, 4)
  const month = date.value.slice(5, 7)
  const monthNames = [
    'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
    'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'
  ]
  const monthIndex = Number(month) - 1

  if (!year || monthIndex < 0 || monthIndex > 11) return date.value
  return `${monthNames[monthIndex]}, ${year}`
}

export function datesAsText (startDate?:Literal, endDate?:Literal):string {
  if (!startDate) return ''
  const start = formatMonthYear(startDate)
  const end = endDate ? formatMonthYear(endDate) : 'Present'
  return `${start} to ${end}`
}

function toMonthDateTime(date?: Literal): string | undefined {
  if (!date?.value) return undefined
  return date.value.slice(0, 7)
}

function renderRole(role: RoleDetails, index: number) {
  if (!role) return html``
  const roleTitleId = `cv-role-title-${index}`
  const rolePeriodId = `cv-role-period-${index}`
  const roleOrgId = `cv-role-org-${index}`
  const roleDescriptionId = `cv-role-description-${index}`

  const ariaDescribedBy = role.description
    ? `${rolePeriodId} ${roleOrgId} ${roleDescriptionId}`
    : `${rolePeriodId} ${roleOrgId}`

  return html`
    <li class="cvRole" role="listitem" aria-labelledby=${roleTitleId} aria-describedby=${ariaDescribedBy}>
    <div class="cvRoleHeader">
      <h4 id=${roleTitleId}>${role.title}</h4>
      <p id=${rolePeriodId} class="cvRolePeriod">
        <time datetime=${toMonthDateTime(role.startDate)}>${formatMonthYear(role.startDate)}</time>
        <span aria-hidden="true"> to </span>
        ${role.endDate
          ? html`<time datetime=${toMonthDateTime(role.endDate)}>${formatMonthYear(role.endDate)}</time>`
          : html`<span>Present</span>`}
      </p>
    </div>
      <p class="cvOrg" id=${roleOrgId}>
        <strong>${role.orgName}</strong>${role.orgLocation ? html` | ${role.orgLocation}` : ''}
      </p>
      ${role.description ? html`
        <div class="cvDescriptionWrap">
          <p class="cvDescriptionText" id=${roleDescriptionId}>${role.description}</p>
          <button
            type="button"
            class="cvDescriptionToggle"
            aria-controls=${roleDescriptionId}
            aria-expanded="false"
            hidden
            @click=${toggleDescription}
          >
            ...more
          </button>
        </div>
      ` : ''}
    </li>
  `
}

function renderRoles(roles: RoleDetails[]) {
  if (!roles || !roles.length) return html``
  return html`${roles.map((role, index) => renderRole(role, index))}`
}

export const CVCard = (
  cvData: RoleDetails[],
  viewerMode: ViewerMode
) => {
  void viewerMode
  const hasRoles = Array.isArray(cvData) && cvData.length > 0
  if (!hasRoles) return html``

  return html`
    <article class="cvCard" aria-label="Resume" data-testid="curriculum-vitae">
      <section class="cvSection">
        <ul role="list" aria-label="Work experience in chronological order">
          ${renderRoles(cvData)}
        </ul>
      </section>
    </article>
  `
}

export function renderCVSection(
  store: LiveStore,
  subject: NamedNode,
  roles: RoleDetails[],
  viewerMode: ViewerMode
) {
  scheduleDescriptionOverflowCheck()

  const cv = CVCard(roles, viewerMode)
  const resumeDetails: RoleDetails[] = roles || []
  const hasResume = cv && cv.strings && cv.strings.join('').trim() !== ''
  const showSection = hasResume || viewerMode === 'owner'

  return showSection ? html`
    <section 
      aria-labelledby="cv-heading" 
      class="section-bg" 
      role="region"
      tabindex="-1"
    >
      <header class="sectionHeader mb-md">
        <h3 id="cv-heading" tabindex="-1">${resumeHeadingText}</h3>
        ${viewerMode === 'owner'
          ? html`
              <button
                type="button"
                class="actionButton"
                aria-label="Edit resume details"
                @click=${(event: Event) => createResumeEditDialog(event, store, subject, resumeDetails, viewerMode)}
              >
                <span class="actionIcon" aria-hidden="true">✎ Edit</span>
              </button>
            `
          : html``}
      </header>
      <div>
        ${hasResume ? cv : html`<p>No resume details added yet.</p>`}
      </div>
    </section>
  ` : ''
}
