import { describe, expect, it } from '@jest/globals'
import axe from 'axe-core'
import { openInputDialog } from '../src/ui/dialog'

describe('Dialog accessibility', () => {
  it('has no accessibility violations for the shared input dialog', async () => {
    const form = document.createElement('form')
    const label = document.createElement('label')
    label.textContent = 'Display name'
    const input = document.createElement('input')
    input.name = 'displayName'
    label.appendChild(input)
    form.appendChild(label)

    const resultPromise = openInputDialog({
      title: 'Edit display name',
      dom: document,
      form,
      headerAction: { type: 'none' }
    })

    const dialog = document.querySelector('#profile-modal') as HTMLDialogElement | null
    expect(dialog).not.toBeNull()

    const results = await axe.run(document.body)
    expect(results.violations.length).toBe(0)

    const cancelButton = document.querySelector('#modal-buttons button[data-cancel]') as HTMLButtonElement | null
    cancelButton?.click()

    await expect(resultPromise).resolves.toBeNull()
  })

  it('keeps the submit label singular after a failed save attempt', async () => {
    const form = document.createElement('form')
    const input = document.createElement('input')
    input.name = 'displayName'
    form.appendChild(input)

    const resultPromise = openInputDialog({
      title: 'Edit display name',
      dom: document,
      form,
      headerAction: { type: 'none' },
      onSave: async () => {
        throw new Error('Save failed')
      }
    })

    const saveButton = document.querySelector('#modal-buttons .btn-primary') as HTMLButtonElement | null
    expect(saveButton?.textContent).toBe('Save Changes')

    saveButton?.click()
    await new Promise(resolve => setTimeout(resolve, 0))

    expect(saveButton?.textContent).toBe('Save Changes')

    const cancelButton = document.querySelector('#modal-buttons button[data-cancel]') as HTMLButtonElement | null
    cancelButton?.click()

    await expect(resultPromise).resolves.toBeNull()
  })

  /* Function below generated by AI Model: GPT-5.4 */
  /* Prompt: add keyboard interaction coverage for the shared dialog so we verify initial focus placement and focus restoration when the dialog is cancelled */
  it('moves focus into the dialog and restores it after cancel', async () => {
    const trigger = document.createElement('button')
    trigger.textContent = 'Open dialog'
    document.body.appendChild(trigger)
    trigger.focus()

    const form = document.createElement('form')
    const label = document.createElement('label')
    label.textContent = 'Display name'
    const input = document.createElement('input')
    input.name = 'displayName'
    label.appendChild(input)
    form.appendChild(label)

    const resultPromise = openInputDialog({
      title: 'Edit display name',
      dom: document,
      form,
      headerAction: { type: 'none' }
    })

    expect(document.activeElement).toBe(input)

    const dialog = document.querySelector('#profile-modal') as HTMLDialogElement | null
    expect(dialog).not.toBeNull()

    const cancelEvent = new Event('cancel', { bubbles: false, cancelable: true })
    dialog?.dispatchEvent(cancelEvent)

    await expect(resultPromise).resolves.toBeNull()
    expect(document.activeElement).toBe(trigger)
  })
})
