import { describe, expect, it } from '@jest/globals'
import { graph, sym } from 'rdflib'
import { createLanguageEditDialog } from '../src/sections/languages/LanguageEditDialog'
import { createSkillsEditDialog } from '../src/sections/skills/SkillsEditDialog'
import { createSocialEditDialog } from '../src/sections/social/SocialEditDialog'
import { getSharedDialogCancelButton, getSharedDialogSaveButton, openInputDialog } from '../src/ui/dialog'
import { runAxe } from './helpers/runAxe'

async function waitForFrame(): Promise<void> {
  await new Promise<void>((resolve) => {
    if (typeof window.requestAnimationFrame === 'function') {
      window.requestAnimationFrame(() => resolve())
      return
    }

    setTimeout(resolve, 0)
  })
}

async function waitForDialogFocus(): Promise<void> {
  await waitForFrame()
  await waitForFrame()
  await waitForFrame()
}

describe('Dialog accessibility', () => {
  it('has no accessibility violations for the shared input dialog', async () => {
    const form = document.createElement('form')
    const label = document.createElement('label')
    label.textContent = 'Display name'
    const input = document.createElement('input')
    input.name = 'displayName'
    label.appendChild(input)
    form.appendChild(label)

    const resultPromise = openInputDialog({
      title: 'Edit display name',
      dom: document,
      form,
      headerAction: { type: 'none' }
    })

    const dialog = document.querySelector('#profile-modal') as HTMLDialogElement | null
    expect(dialog).not.toBeNull()

    const results = await runAxe(document.body)
    expect(results.violations.length).toBe(0)

    const cancelButton = getSharedDialogCancelButton(document)
    cancelButton?.click()

    await expect(resultPromise).resolves.toBeNull()
  })

  it('keeps the submit label singular after a failed save attempt', async () => {
    const form = document.createElement('form')
    const input = document.createElement('input')
    input.name = 'displayName'
    form.appendChild(input)

    const resultPromise = openInputDialog({
      title: 'Edit display name',
      dom: document,
      form,
      headerAction: { type: 'none' },
      onSave: async () => {
        throw new Error('Save failed')
      }
    })

    const saveButton = getSharedDialogSaveButton(document)
    expect(saveButton?.textContent).toBe('Save Changes')

    saveButton?.click()
    await new Promise(resolve => setTimeout(resolve, 0))

    expect(saveButton?.textContent).toBe('Save Changes')

    const cancelButton = getSharedDialogCancelButton(document)
    cancelButton?.click()

    await expect(resultPromise).resolves.toBeNull()
  })

  it('makes the dialog body inert while save is in progress', async () => {
    let resolveSave: (() => void) | undefined

    const form = document.createElement('form')
    const input = document.createElement('input')
    input.name = 'displayName'
    form.appendChild(input)

    const resultPromise = openInputDialog({
      title: 'Edit display name',
      dom: document,
      form,
      headerAction: { type: 'none' },
      onSave: () => new Promise<void>((resolve) => {
        resolveSave = resolve
      })
    })

    input.focus()

    const dialog = document.querySelector('#profile-modal') as HTMLDialogElement | null
    const description = document.querySelector('#modal-desc') as HTMLDivElement | null
    const overlay = document.querySelector('#modal-saving-overlay') as HTMLDivElement | null
    const saveButton = getSharedDialogSaveButton(document)

    saveButton?.click()
    await new Promise(resolve => setTimeout(resolve, 0))

    expect(dialog?.classList.contains('modal--saving')).toBe(true)
    expect(dialog?.getAttribute('aria-busy')).toBe('true')
    expect(description?.hasAttribute('inert')).toBe(true)
    expect(document.activeElement).not.toBe(input)
    expect(overlay?.hidden).toBe(false)

    if (resolveSave) {
      resolveSave()
    }
    await expect(resultPromise).resolves.toEqual({ displayName: '' })
  })

  /* Function below generated by AI Model: GPT-5.4 */
  /* Prompt: add keyboard interaction coverage for the shared dialog so we verify initial focus placement and focus restoration when the dialog is cancelled */
  it('moves focus into the dialog and restores it after cancel', async () => {
    const trigger = document.createElement('button')
    trigger.textContent = 'Open dialog'
    document.body.appendChild(trigger)
    trigger.focus()

    const form = document.createElement('form')
    const label = document.createElement('label')
    label.textContent = 'Display name'
    const input = document.createElement('input')
    input.name = 'displayName'
    label.appendChild(input)
    form.appendChild(label)

    const resultPromise = openInputDialog({
      title: 'Edit display name',
      dom: document,
      form,
      headerAction: { type: 'none' }
    })

    expect(document.activeElement).toBe(input)

    const dialog = document.querySelector('#profile-modal') as HTMLDialogElement | null
    expect(dialog).not.toBeNull()

    const cancelEvent = new Event('cancel', { bubbles: false, cancelable: true })
    dialog?.dispatchEvent(cancelEvent)

    await expect(resultPromise).resolves.toBeNull()
    expect(document.activeElement).toBe(trigger)
  })

  it('opens social, skills, and language dialogs with focus on the first field while keeping popups closed', async () => {
    const store = graph() as any
    const subject = sym('https://example.com/profile/card#me')
    const trigger = document.createElement('button')
    trigger.textContent = 'Open dialog'
    document.body.appendChild(trigger)

    const socialPromise = createSocialEditDialog(
      { currentTarget: trigger } as unknown as Event,
      store,
      subject,
      [],
      'owner'
    )

    await waitForDialogFocus()

    const socialSelect = document.querySelector('solid-ui-select[data-social-account-row-index="0"]') as HTMLElement | null
    expect(socialSelect).not.toBeNull()
    expect(socialSelect?.shadowRoot?.activeElement?.tagName).toBe('BUTTON')
    expect(socialSelect?.hasAttribute('popup-open')).toBe(false)

    getSharedDialogCancelButton(document)?.click()
    await expect(socialPromise).resolves.toBeUndefined()

    const skillsPromise = createSkillsEditDialog(
      { currentTarget: trigger } as unknown as Event,
      store,
      subject,
      [],
      'owner'
    )

    await waitForDialogFocus()

    const skillsCombobox = document.querySelector('solid-ui-combobox[data-skill-row-index="0"]') as (HTMLElement & { _popupOpen?: boolean }) | null
    expect(skillsCombobox).not.toBeNull()
    expect(skillsCombobox?.shadowRoot?.activeElement?.tagName).toBe('INPUT')
    expect(skillsCombobox?._popupOpen).toBe(false)

    getSharedDialogCancelButton(document)?.click()
    await expect(skillsPromise).resolves.toBeUndefined()

    const languagePromise = createLanguageEditDialog(
      { currentTarget: trigger } as unknown as Event,
      store,
      subject,
      [],
      'owner'
    )

    await waitForDialogFocus()

    const languageCombobox = document.querySelector('solid-ui-combobox[data-language-row-index="0"]') as (HTMLElement & { _popupOpen?: boolean }) | null
    expect(languageCombobox).not.toBeNull()
    expect(languageCombobox?.shadowRoot?.activeElement?.tagName).toBe('INPUT')
    expect(languageCombobox?._popupOpen).toBe(false)

    getSharedDialogCancelButton(document)?.click()
    await expect(languagePromise).resolves.toBeUndefined()
  })
})
