// This code was generated by GPT-5.4 in GitHub Copilot.
import { beforeEach, describe, expect, it, jest } from '@jest/globals'
import { parse, sym } from 'rdflib'
import { store } from 'solid-logic'
import { presentProfileViewModel } from '../src/ProfileViewModelPresenter'
import { presentProjects } from '../src/sections/projects/selectors'

jest.mock('../src/sections/projects/selectors', () => {
  const actual = jest.requireActual<typeof import('../src/sections/projects/selectors')>(
    '../src/sections/projects/selectors'
  )
  return {
    ...actual,
    presentProjects: jest.fn(actual.presentProjects)
  }
})

const actualProjectSelectors = jest.requireActual('../src/sections/projects/selectors') as typeof import('../src/sections/projects/selectors')
const mockedPresentProjects = presentProjects as jest.MockedFunction<typeof presentProjects>

const subject = sym('https://janedoe.example/profile/card#me')
const profileDoc = subject.doc()
const projectNode = sym('https://projects.example/community#profile-pane')
const projectDoc = projectNode.doc()

const profileTurtle = `
  @prefix : <#>.
  @prefix foaf: <http://xmlns.com/foaf/0.1/> .
  @prefix org: <http://www.w3.org/ns/org#> .
  @prefix schema: <http://schema.org/> .
  @prefix soc: <https://solidos.github.io/profile-pane/src/ontology/socialMedia.ttl#> .
  @prefix solid: <http://www.w3.org/ns/solid/terms#> .
  @prefix vcard: <http://www.w3.org/2006/vcard/ns#> .
  @prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

  :me
    a foaf:Person;
    foaf:name "Jane Doe";
    vcard:note "Builds profile features for SolidOS.";
    vcard:role "Staff Engineer";
    vcard:organization-name "SolidOS";
    schema:skills :skill1;
    schema:knowsLanguage ( <https://www.w3.org/ns/iana/language-code/en> );
    foaf:account ( :account1 );
    solid:community <https://projects.example/community#profile-pane>;
    vcard:hasEmail [
      a vcard:Work;
      vcard:value <mailto:jane@example.com>
    ];
    vcard:hasTelephone [
      a vcard:Work;
      vcard:value <tel:+15551234567>
    ];
    vcard:hasAddress [
      vcard:street-address "123 Solid Lane";
      vcard:locality "Boston";
      vcard:country-name "USA"
    ].

  :skill1 solid:publicId <http://data.europa.eu/esco/skill/1234> .
  <http://data.europa.eu/esco/skill/1234> schema:name "TypeScript" .

  :role1
    a solid:CurrentRole;
    org:member :me;
    org:organization :org1;
    vcard:role "Staff Engineer";
    schema:startDate "2022-01-01"^^xsd:date;
    schema:description "Ships profile features.".

  :org1
    schema:name "SolidOS";
    org:location "Remote".

  :education1
    a schema:EducationalOccupationalCredential;
    org:member :me;
    schema:name "State University";
    schema:educationalCredentialAwarded "BSc Computer Science";
    schema:location "Boston";
    schema:startDate "2018-09-01";
    schema:endDate "2022-06-01";
    schema:description "Learned software engineering.".

  :account1
    a soc:LinkedInAccount;
    foaf:accountName "jane-doe".
`

const projectTurtle = `
  @prefix : <#>.
  @prefix foaf: <http://xmlns.com/foaf/0.1/> .
  @prefix schema: <http://schema.org/> .
  @prefix vcard: <http://www.w3.org/2006/vcard/ns#> .

  :profile-pane
    a schema:Project;
    foaf:name "Profile Pane";
    vcard:organization-name "SolidOS".
`

describe('presentProfileViewModel integration', () => {
  beforeEach(() => {
    store.removeDocument(profileDoc)
    store.removeDocument(projectDoc)
    ;(store as any).fetcher = {
      ...((store as any).fetcher || {}),
      load: jest.fn(async () => undefined)
    }
    mockedPresentProjects.mockImplementation(actualProjectSelectors.presentProjects)
    parse(profileTurtle, store, profileDoc.uri, 'text/turtle')
    parse(projectTurtle, store, projectDoc.uri, 'text/turtle')
  })

  it('returns the complete aggregated presenter contract from one profile fixture', async () => {
    const viewModel = await presentProfileViewModel(subject, store as any)

    expect(Object.keys(viewModel).sort()).toEqual([
      'bioDetails',
      'contactInfo',
      'cvDetails',
      'education',
      'languages',
      'profileDetails',
      'projects',
      'skills',
      'social'
    ])

    expect(viewModel.profileDetails.name).toBe('Jane Doe')
    expect(viewModel.profileDetails.jobTitle).toBe('Staff Engineer')
    expect(viewModel.bioDetails.description).toBe('Builds profile features for SolidOS.')
    expect(viewModel.cvDetails[0].orgName).toBe('SolidOS')
    expect(viewModel.projects[0].title).toBe('Profile Pane')
    expect(viewModel.skills[0].name).toBe('TypeScript')
    expect(viewModel.languages[0].name).toBe('English')
    expect(viewModel.education[0].school).toBe('State University')
    expect(viewModel.contactInfo.emails[0].valueNode.value).toBe('mailto:jane@example.com')
    expect(viewModel.contactInfo.phones[0].valueNode.value).toBe('tel:+15551234567')
    expect(viewModel.contactInfo.addresses[0].locality).toBe('Boston')
    expect(viewModel.social.accounts[0].homepage).toContain('linkedin.com')
  })

  it('surfaces async selector failures from the project branch', async () => {
    mockedPresentProjects.mockRejectedValueOnce(new Error('project selector failed'))

    await expect(presentProfileViewModel(subject, store as any)).rejects.toThrow(
      'project selector failed'
    )
  })
})