// This code was generated by GPT-5.4 in GitHub Copilot.
import { beforeEach, describe, expect, it, jest } from '@jest/globals'
import { render } from 'lit-html'
import { parse, sym } from 'rdflib'
import type { DataBrowserContext } from 'pane-registry'
import { store } from 'solid-logic'
import { presentProfileViewModel } from '../src/ProfileViewModelPresenter'
import { ProfileView } from '../src/ProfileView'

const subject = sym('https://janedoe.example/profile/card#me')
const profileDoc = subject.doc()
const projectNode = sym('https://projects.example/community#profile-pane')
const projectDoc = projectNode.doc()

const profileTurtle = `
  @prefix : <#>.
  @prefix foaf: <http://xmlns.com/foaf/0.1/> .
  @prefix org: <http://www.w3.org/ns/org#> .
  @prefix schema: <http://schema.org/> .
  @prefix soc: <https://solidos.github.io/profile-pane/src/ontology/socialMedia.ttl#> .
  @prefix solid: <http://www.w3.org/ns/solid/terms#> .
  @prefix vcard: <http://www.w3.org/2006/vcard/ns#> .
  @prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

  :me
    a foaf:Person;
    foaf:name "Jane Doe";
    vcard:note "Builds profile features for SolidOS.";
    vcard:role "Staff Engineer";
    vcard:organization-name "SolidOS";
    schema:skills :skill1;
    schema:knowsLanguage ( <https://www.w3.org/ns/iana/language-code/en> );
    foaf:account ( :account1 );
    solid:community <https://projects.example/community#profile-pane>;
    vcard:hasEmail [
      a vcard:Work;
      vcard:value <mailto:jane@example.com>
    ];
    vcard:hasTelephone [
      a vcard:Work;
      vcard:value <tel:+15551234567>
    ];
    vcard:hasAddress [
      vcard:street-address "123 Solid Lane";
      vcard:locality "Boston";
      vcard:country-name "USA"
    ].

  :skill1 solid:publicId <http://data.europa.eu/esco/skill/1234> .
  <http://data.europa.eu/esco/skill/1234> schema:name "TypeScript" .

  :role1
    a solid:CurrentRole;
    org:member :me;
    org:organization :org1;
    vcard:role "Staff Engineer";
    schema:startDate "2022-01-01"^^xsd:date;
    schema:description "Ships profile features.".

  :org1
    schema:name "SolidOS";
    org:location "Remote".

  :education1
    a schema:EducationalOccupationalCredential;
    org:member :me;
    schema:name "State University";
    schema:educationalCredentialAwarded "BSc Computer Science";
    schema:location "Boston";
    schema:startDate "2018-09-01";
    schema:endDate "2022-06-01";
    schema:description "Learned software engineering.".

  :account1
    a soc:LinkedInAccount;
    foaf:accountName "jane-doe".
`

const projectTurtle = `
  @prefix : <#>.
  @prefix foaf: <http://xmlns.com/foaf/0.1/> .
  @prefix schema: <http://schema.org/> .
  @prefix vcard: <http://www.w3.org/2006/vcard/ns#> .

  :profile-pane
    a schema:Project;
    foaf:name "Profile Pane";
    vcard:organization-name "SolidOS".
`

function createContext(): DataBrowserContext {
  return {
    dom: document,
    getOutliner: () => null,
    session: {
      info: {
        isLoggedIn: false,
        webId: null,
      },
      paneRegistry: {
        byName: () => ({
          render: () => document.createElement('div')
        })
      },
      store,
      logic: {}
    },
  } as unknown as DataBrowserContext
}

describe('Profile view composition', () => {
  let context: DataBrowserContext

  beforeEach(() => {
    store.removeDocument(profileDoc)
    store.removeDocument(projectDoc)
    ;(store as any).fetcher = {
      ...((store as any).fetcher || {}),
      load: jest.fn(async () => undefined)
    }
    parse(profileTurtle, store, profileDoc.uri, 'text/turtle')
    parse(projectTurtle, store, projectDoc.uri, 'text/turtle')
    context = createContext()
  })

  it('aggregates all major presenter branches from one profile fixture', async () => {
    const viewModel = await presentProfileViewModel(subject, store as any)

    expect(viewModel.profileDetails.name).toBe('Jane Doe')
    expect(viewModel.profileDetails.jobTitle).toBe('Staff Engineer')

    expect(viewModel.bioDetails.description).toBe('Builds profile features for SolidOS.')

    expect(viewModel.cvDetails).toHaveLength(1)
    expect(viewModel.cvDetails[0].title).toBe('Staff Engineer')
    expect(viewModel.cvDetails[0].orgName).toBe('SolidOS')

    expect(viewModel.projects).toHaveLength(1)
    expect(viewModel.projects[0].title).toBe('Profile Pane')

    expect(viewModel.skills).toHaveLength(1)
    expect(viewModel.skills[0].name).toBe('TypeScript')

    expect(viewModel.languages).toHaveLength(1)
    expect(viewModel.languages[0].name).toBe('English')

    expect(viewModel.contactInfo.emails).toHaveLength(1)
    expect(viewModel.contactInfo.emails[0].valueNode.value).toBe('mailto:jane@example.com')
    expect(viewModel.contactInfo.phones).toHaveLength(1)
    expect(viewModel.contactInfo.phones[0].valueNode.value).toBe('tel:+15551234567')
    expect(viewModel.contactInfo.addresses).toHaveLength(1)
    expect(viewModel.contactInfo.addresses[0].locality).toBe('Boston')

    expect(viewModel.social.accounts).toHaveLength(1)
    expect(viewModel.social.accounts[0].homepage).toContain('linkedin.com')

    expect(viewModel.education).toHaveLength(1)
    expect(viewModel.education[0].school).toBe('State University')
  })

  it('renders the assembled profile view from the aggregated fixture', async () => {
    const container = document.createElement('div')
    document.body.appendChild(container)

    const result = await ProfileView(subject, context)
    render(result, container)

    expect(container.querySelector('#profile-name')?.textContent).toBe('Jane Doe')
    expect(container.textContent).toContain('Builds profile features for SolidOS.')
    expect(container.textContent).toContain('Staff Engineer')
    expect(container.textContent).toContain('Profile Pane')
    expect(container.textContent).toContain('TypeScript')
    expect(container.textContent).toContain('English')
    expect(container.textContent).toContain('jane@example.com')
    expect(container.textContent).toContain('Link to Profile')
    expect(container.querySelector('[data-testid="qrcode-card"]')).not.toBeNull()

    container.remove()
  })
})