import { LiveStore, NamedNode, Node, sym } from 'rdflib'
import { ns, utils, widgets } from 'solid-ui'
import { ProjectDetails } from './types'

/* The following functions communityNodesForSubject and ensureProjectDocumentsLoaded 
   and a few updates in presentProjects are generated by AI Model: GPT-5.3-Codex */
/* Prompt: Image and business type are not displaying, could it be that I didn't load
  the document? */
function communityNodesForSubject(subject: NamedNode, store: LiveStore, doc: NamedNode): Node[] {
  const inProfileDoc = store.each(subject, ns.solid('community'), null, doc) as Node[]
  const inAnyDoc = store.each(subject, ns.solid('community'), null, null) as Node[]

  const seen = new Set<string>()
  const nodes: Node[] = []
  for (const node of [...inProfileDoc, ...inAnyDoc]) {
    const key = `${(node as any)?.termType || ''}:${(node as any)?.value || ''}`
    if (seen.has(key)) continue
    seen.add(key)
    nodes.push(node)
  }
  return nodes
}

export async function ensureProjectDocumentsLoaded(subject: NamedNode, store: LiveStore): Promise<void> {
  const profileDoc = subject.doc()
  const fetcher = (store as any)?.fetcher

  if (!fetcher || typeof fetcher.load !== 'function') {
    return
  }

  const communityNodes = communityNodesForSubject(subject, store, profileDoc)

  const docsToLoad = new Map<string, NamedNode>()
  for (const node of communityNodes) {
    if (!node || node.termType !== 'NamedNode') continue
    const projectDoc = (node as NamedNode).doc()
    docsToLoad.set(projectDoc.value, projectDoc)
  }

  if (!docsToLoad.size) {
    return
  }

  await Promise.all(
    Array.from(docsToLoad.values()).map(async (doc) => {
      try {
        await fetcher.load(doc)
      } catch {
        // Ignore individual project doc load failures so one bad doc doesn't block others.
      }
    })
  )
}

function projectNodeToUrl(node: Node): string {
  if (!node) return ''
  if ((node as any).termType === 'NamedNode') return (node as any).value || ''
  if ((node as any).termType === 'Literal') return (node as any).value || ''
  return ''
}

function normalizeUrlKey(value: string): string {
  const text = (value || '').trim()
  if (!text) return ''
  try {
    return new URL(text).href
  } catch {
    return text
  }
}

function toProjectNamedNode(node: Node, url: string): NamedNode | null {
  if (node && node.termType === 'NamedNode') return node as NamedNode
  try {
    return sym(url)
  } catch {
    return null
  }
}

export async function presentProjects(subject: NamedNode, store: LiveStore): Promise<ProjectDetails[]> {
  await ensureProjectDocumentsLoaded(subject, store)

  const doc = subject.doc()
  const seen = new Set<string>()
  const communityNodes = communityNodesForSubject(subject, store, doc)

  const projects = communityNodes
    .map((communityNode) => {
      const url = projectNodeToUrl(communityNode as Node)
      const key = normalizeUrlKey(url)
      const projectNode = toProjectNamedNode(communityNode as Node, url)
      const projectDoc = projectNode?.doc()

      const name = projectNode
        ? store.anyValue(projectNode, ns.foaf('name'), null, projectDoc || null) || undefined
        : undefined
      const orgName = projectNode
        ? store.anyValue(projectNode, ns.vcard('organization-name'), null, projectDoc || null) || undefined
        : undefined

      const title = name || (projectNode ? utils.label(projectNode) : utils.label(key))
      const imageUrl = projectNode
        ? widgets.findImage(projectNode) ||
          ((widgets as any).findImageFromURI?.(projectNode) ?? undefined)
        : undefined
      let types: NamedNode[] = []
      if (projectNode) {
        types = store.each(projectNode, ns.rdf('type'), null, projectDoc || null) as NamedNode[]
      }

      const category = types.find(
        (t) =>
          t.termType === 'NamedNode' &&
          (t.value === ns.schema('Project').value || t.value === ns.schema('Community').value)
        )

      const categoryValue: ProjectDetails['category'] =
        category?.value === ns.schema('Project').value
          ? 'project'
          : category?.value === ns.schema('Community').value
            ? 'community'
            : 'unknown'

      if (!url || !key || seen.has(key)) {
        return null
      }

      seen.add(key)

      return {
        url,
        title,
        name,
        orgName,
        imageUrl,
        category: categoryValue,
        entryNode: communityNode as Node
      } as ProjectDetails
    })
    .filter((project): project is ProjectDetails => Boolean(project))

  return projects
}
