import { LiveStore, NamedNode, Node, sym } from 'rdflib'
import { ns, utils, widgets } from 'solid-ui'
import { ProjectDetails } from './types'
import { expandRdfList } from '../shared/rdfList'

/* The following functions communityNodesForSubject and ensureProjectDocumentsLoaded 
   and a few updates in presentProjects are generated by AI Model: GPT-5.3-Codex */
/* Prompt: Image and business type are not displaying, could it be that I didn't load
  the document? */
function communityNodesForSubject(subject: NamedNode, store: LiveStore, doc: NamedNode): Node[] {
  const inProfileDoc = store.each(subject, ns.solid('community'), null, doc) as Node[]
  const inAnyDoc = store.each(subject, ns.solid('community'), null, null) as Node[]
  const rawNodes = [...inProfileDoc, ...inAnyDoc]

  const expandedNodes = rawNodes.flatMap((node) => {
    const hasCollectionElements = Array.isArray((node as any)?.elements)
    const isListByTriples =
      (node.termType === 'BlankNode' || node.termType === 'NamedNode') &&
      Boolean(store.any(node as NamedNode, ns.rdf('first')))

    return hasCollectionElements || isListByTriples
      ? expandRdfList(store, node)
      : [node]
  })

  const seen = new Set<string>()
  const nodes: Node[] = []
  for (const node of expandedNodes) {
    const key = `${(node as any)?.termType || ''}:${(node as any)?.value || ''}`
    if (seen.has(key)) continue
    seen.add(key)
    nodes.push(node)
  }
  return nodes
}

function clearStaleRequestedState(fetcher: any, docUrl: string): unknown {
  const requested = fetcher?.requested
  if (!requested || typeof requested !== 'object') return undefined

  const previous = requested[docUrl]
  const shouldClear =
    (typeof previous === 'string' && previous !== 'requested' && previous !== 'done') ||
    (typeof previous === 'number' && previous >= 400)

  if (shouldClear) {
    delete requested[docUrl]
  }

  return previous
}

function linkedProjectNodeFromCommunityNode(node: Node, store: LiveStore): NamedNode | null {
  if (!node) return null
  if (node.termType === 'NamedNode') return node as NamedNode
  if (node.termType === 'Literal') {
    try {
      return sym(node.value)
    } catch {
      return null
    }
  }
  if (node.termType !== 'BlankNode') return null

  const candidatePredicates = [
    ns.solid('publicId'),
    ns.schema('url'),
    ns.foaf('homepage'),
    ns.rdfs('seeAlso'),
    ns.schema('sameAs'),
    ns.schema('mainEntityOfPage')
  ]

  for (const predicate of candidatePredicates) {
    const linked = store.any(node as NamedNode, predicate) as Node | null
    if (!linked?.value) continue

    if (linked.termType === 'NamedNode') {
      return linked as NamedNode
    }

    if (linked.termType === 'Literal') {
      try {
        return sym(linked.value)
      } catch {
        // Keep trying the next predicate.
      }
    }
  }

  const outgoing = store.statementsMatching(node as NamedNode, null, null, null)
  const firstNamedNode = outgoing.find((statement) => statement.object.termType === 'NamedNode')
  if (firstNamedNode?.object?.value) {
    return firstNamedNode.object as NamedNode
  }

  return null
}

export async function ensureProjectDocumentsLoaded(subject: NamedNode, store: LiveStore): Promise<void> {
  const profileDoc = subject.doc()
  const fetcher = (store as any)?.fetcher

  console.info('[profile-pane/projects] ensureProjectDocumentsLoaded:start', {
    subject: subject.value,
    profileDoc: profileDoc.value,
    hasFetcher: Boolean(fetcher && typeof fetcher.load === 'function')
  })

  if (!fetcher || typeof fetcher.load !== 'function') {
    console.warn('[profile-pane/projects] ensureProjectDocumentsLoaded:no-fetcher')
    return
  }

  const communityNodes = communityNodesForSubject(subject, store, profileDoc)

  const docsToLoad = new Map<string, NamedNode>()
  for (const node of communityNodes) {
    const linkedProjectNode = linkedProjectNodeFromCommunityNode(node, store)
    if (!linkedProjectNode) continue
    const projectDoc = linkedProjectNode.doc()
    docsToLoad.set(projectDoc.value, projectDoc)
  }

  console.info('[profile-pane/projects] ensureProjectDocumentsLoaded:candidates', {
    communityNodes: communityNodes.length,
    docsToLoad: docsToLoad.size
  })

  if (!docsToLoad.size) {
    console.info('[profile-pane/projects] ensureProjectDocumentsLoaded:no-docs')
    return
  }

  await Promise.all(
    Array.from(docsToLoad.values()).map(async (doc) => {
      const previousRequested = clearStaleRequestedState(fetcher, doc.value)
      try {
        console.debug('[profile-pane/projects] loading linked profile document', {
          doc: doc.value,
          previousRequested
        })
        await fetcher.load(doc)
        const statementsInDoc = store.statementsMatching(undefined, undefined, undefined, doc).length
        console.debug('[profile-pane/projects] loaded linked profile document', {
          doc: doc.value,
          statementsInDoc
        })
      } catch {
        console.warn('[profile-pane/projects] failed to load linked profile document', {
          doc: doc.value,
          requested: fetcher?.requested?.[doc.value]
        })
        // Ignore individual project doc load failures so one bad doc doesn't block others.
      }
    })
  )
}

function projectNodeToUrl(node: Node): string {
  if (!node) return ''
  if ((node as any).termType === 'NamedNode') return (node as any).value || ''
  if ((node as any).termType === 'Literal') return (node as any).value || ''
  return ''
}

function normalizeUrlKey(value: string): string {
  const text = (value || '').trim()
  if (!text) return ''
  try {
    return new URL(text).href
  } catch {
    return text
  }
}

function toProjectNamedNode(node: Node, url: string): NamedNode | null {
  if (node && node.termType === 'NamedNode') return node as NamedNode
  try {
    return sym(url)
  } catch {
    return null
  }
}

export async function presentProjects(subject: NamedNode, store: LiveStore): Promise<ProjectDetails[]> {
  await ensureProjectDocumentsLoaded(subject, store)

  const doc = subject.doc()
  const seen = new Set<string>()
  const communityNodes = communityNodesForSubject(subject, store, doc)

  const projects = communityNodes
    .map((communityNode) => {
      const linkedProjectNode = linkedProjectNodeFromCommunityNode(communityNode as Node, store)
      const url = linkedProjectNode?.value || projectNodeToUrl(communityNode as Node)
      const key = normalizeUrlKey(url)
      const projectNode = linkedProjectNode || toProjectNamedNode(communityNode as Node, url)
      const projectDoc = projectNode?.doc()

      const name = projectNode
        ? store.anyValue(projectNode, ns.foaf('name'), null, projectDoc || null) || undefined
        : undefined
      const orgName = projectNode
        ? store.anyValue(projectNode, ns.vcard('organization-name'), null, projectDoc || null) || undefined
        : undefined

      const title = name || (projectNode ? utils.label(projectNode) : utils.label(key))
      const imageUrl = projectNode
        ? widgets.findImage(projectNode) ||
          ((widgets as any).findImageFromURI?.(projectNode) ?? undefined)
        : undefined
      let types: NamedNode[] = []
      if (projectNode) {
        types = store.each(projectNode, ns.rdf('type'), null, projectDoc || null) as NamedNode[]
      }

      const category = types.find(
        (t) =>
          t.termType === 'NamedNode' &&
          (t.value === ns.schema('Project').value || t.value === ns.schema('Community').value)
        )

      const categoryValue: ProjectDetails['category'] =
        category?.value === ns.schema('Project').value
          ? 'project'
          : category?.value === ns.schema('Community').value
            ? 'community'
            : 'unknown'

      if (!url || !key || seen.has(key)) {
        return null
      }

      seen.add(key)

      return {
        url,
        title,
        name,
        orgName,
        imageUrl,
        category: categoryValue,
        entryNode: communityNode as Node
      } as ProjectDetails
    })
    .filter((project): project is ProjectDetails => Boolean(project))

  return projects
}
