export const userNotLoggedInErrorMessage = 'Current user not found! Not logged in?'
export const friendWasAddedSuccesMessage = 'Friend was added!'
export const friendExistsMessage = 'Friend already exists'
export const loadingMessage = 'Loading...'
export const ownerLoginRequiredDialogMessageText = 'You need to log in as the profile owner to save contact updates.'

export const saveContactUpdatesFailedPrefixText = 'Could not save contact updates.'
export const saveHeadingUpdatesFailedPrefixText = 'Could not save heading updates.'
export const saveLanguageUpdatesFailedPrefixText = 'Could not save language updates.'
export const saveResumeUpdatesFailedPrefixText = 'Could not save resume updates.'
export const saveEducationUpdatesFailedPrefixText = 'Could not save education updates.'
export const saveProjectsUpdatesFailedPrefixText = 'Could not save projects updates.'
export const saveSocialUpdatesFailedPrefixText = 'Could not save social accounts updates.'
export const saveBioUpdatesFailedPrefixText = 'Could not save bio updates.'

export const mutationSaveContactInfoFailedPrefixText = 'Failed to save contact info:'
export const mutationSaveLanguagesFailedPrefixText = 'Failed to save languages:'
export const mutationSaveSkillsFailedPrefixText = 'Failed to save skills:'
export const mutationSaveResumeFailedPrefixText = 'Failed to save resume:'
export const mutationEducationFailedPrefixText = 'Failed to save education:'
export const resumeUpdateEntryNotFoundErrorMessageText = 'Could not find existing resume entry for update. Please reload profile data and try again.'
export const updaterUnsupportedStoreErrorMessageText = 'Store does not support updates'
export const fallbackSaveUpdatesErrorMessageText = 'Failed to save updates'
