import { html, TemplateResult } from 'lit-html'
import { LiveStore, NamedNode } from 'rdflib'
import { ns, utils } from 'solid-ui'
import { scanQrToConnectText } from '../../texts'
import * as qrcode from 'qrcode'
/* Part of this code was generated by AI Model: GPT-5.3-Codex */
/* Prompt: The QRCode has a label "link to profile" but it should
 be a VCARD with name, and link to profile. So when you scan it 
 it goes into your contacts. That's the current way works, IIRC. */
type LegacySubjectArg = NamedNode | string

function isNamedNodeLike(value: unknown): value is NamedNode {
  return Boolean(value && typeof value === 'object' && typeof (value as any).uri === 'string')
}

function isStoreLike(value: unknown): value is LiveStore {
  return Boolean(value && typeof value === 'object' && typeof (value as any).any === 'function')
}

function resolveQRCodeArgs(
  arg1: LegacySubjectArg,
  arg2?: unknown,
  arg3?: unknown
): { subject: NamedNode, store?: LiveStore } {
  if (isNamedNodeLike(arg1)) {
    return {
      subject: arg1,
      store: isStoreLike(arg2) ? arg2 : undefined
    }
  }

  if (isNamedNodeLike(arg3)) {
    return {
      subject: arg3,
      store: isStoreLike(arg2) ? arg2 : undefined
    }
  }

  throw new Error('QRCodeCard requires a profile subject NamedNode.')
}

function normalizeEmail(value: string): string {
  return (value || '').trim().replace(/^mailto:/i, '')
}

function normalizeTelephone(value: string): string {
  return (value || '').trim().replace(/^tel:/i, '')
}

function isEmailValue(value: string): boolean {
  const normalized = (value || '').trim()
  if (!normalized) return false
  if (/^mailto:/i.test(normalized)) return true
  return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(normalized)
}

function isPhoneValue(value: string): boolean {
  const normalized = (value || '').trim()
  if (!normalized) return false
  if (/^tel:/i.test(normalized)) return true
  return /^[+()\-\s\d]{5,}$/.test(normalized)
}

function firstContactValue(
  store: LiveStore | undefined,
  subject: NamedNode,
  predicate: NamedNode,
  kind: 'email' | 'tel'
): string {
  if (!store) return ''

  const candidates = store.each(subject, predicate)
  const isExpectedValue = kind === 'email' ? isEmailValue : isPhoneValue
  for (const node of candidates) {
    if (!node) continue

    const direct = (node as any).value
    if (typeof direct === 'string' && isExpectedValue(direct)) {
      return kind === 'email' ? normalizeEmail(direct) : normalizeTelephone(direct)
    }

    if (node.termType === 'NamedNode' || node.termType === 'BlankNode') {
      const doc = subject.doc()
      const inDocStatements = store.statementsMatching(node as any, ns.vcard('value'), null, doc)
      const anyGraphStatements = store.statementsMatching(node as any, ns.vcard('value'))

      for (const statement of [...inDocStatements, ...anyGraphStatements]) {
        const viaValue = statement.object?.value
        if (typeof viaValue === 'string' && isExpectedValue(viaValue)) {
          return kind === 'email' ? normalizeEmail(viaValue) : normalizeTelephone(viaValue)
        }
      }
    }
  }

  return ''
}

const qrCodeRenderOptions = {
  type: 'svg' as const,
  color: {
    dark: '#000000',
    light: '#ffffff'
  }
}

function renderQRCodeSvg(value: string): Promise<string> {
  return new Promise((resolve, reject) => {
    qrcode.toString(value, qrCodeRenderOptions, (error, svg) => {
      if (error) {
        reject(error)
        return
      }

      resolve(svg)
    })
  })
}

export async function hydrateQRCodeElement(QRCodeElement: HTMLElement): Promise<void> {
  const value = QRCodeElement.getAttribute('data-value')
  if (!value) {
    console.error('QRCode data-value missing')
    return
  }

  const imageContainer = QRCodeElement.querySelector('div[aria-hidden="true"]') as HTMLElement | null
  if (!imageContainer) {
    console.error('QRCode image container missing')
    return
  }

  try {
    imageContainer.innerHTML = await renderQRCodeSvg(value)
  } catch (error) {
    console.error('QRcode error!', error)
  }
}

export async function hydrateQRCodes(root: ParentNode): Promise<void> {
  const QRCodeElements = Array.from(root.querySelectorAll('.qrcode-card')) as HTMLElement[]
  if (!QRCodeElements.length) {
    console.error('QRCode Ele missing')
    return
  }

  await Promise.all(QRCodeElements.map((element) => hydrateQRCodeElement(element)))
}

export const QRCodeCard = (
  arg1: LegacySubjectArg,
  arg2?: unknown,
  arg3?: unknown
): TemplateResult => {
  const { subject, store } = resolveQRCodeArgs(arg1, arg2, arg3)
  const name = utils.label(subject)

  const escapeVCardValue = (value: string): string => {
    return (value || '')
      .replace(/\\/g, '\\\\')
      .replace(/;/g, '\\;')
      .replace(/,/g, '\\,')
      .replace(/\r?\n/g, '\\n')
  }

  const safeName = escapeVCardValue(name || subject.uri)
  const safeUrl = escapeVCardValue(subject.uri)
  const email = firstContactValue(store, subject, ns.vcard('hasEmail'), 'email')
  const telephone = firstContactValue(store, subject, ns.vcard('hasTelephone'), 'tel')
  const vCardLines = [
    'BEGIN:VCARD',
    'VERSION:4.0',
    `FN:${safeName}`,
    `URL:${safeUrl}`,
  ]

  if (email) {
    vCardLines.push(`EMAIL;TYPE=internet:${escapeVCardValue(email)}`)
  }

  if (telephone) {
    vCardLines.push(`TEL:${escapeVCardValue(telephone)}`)
  }

  vCardLines.push('END:VCARD')
  const vCard = vCardLines.join('\r\n')

  return html`
    <figure 
      class="qrcode-card flex-column-center"
      data-value="${vCard}"
      data-testid="qrcode-card"
      aria-labelledby="qr-code-caption"
      role="img"
      aria-describedby="qr-code-description"
    >
      <div 
        aria-hidden="true"
      ></div>
      <figcaption 
        id="qr-code-caption" 
        class="qrcode-card__caption"
      >
        ${scanQrToConnectText}
      </figcaption>
      <div 
        id="qr-code-description" 
        class="sr-only"
      >
        This is a static QR code containing vCard information for ${name}, including profile URL ${subject.uri}. The QR code is not interactive.
      </div>
    </figure>
  `
}
