import { blankNode, LiveStore, NamedNode, Node, st, literal, sym } from 'rdflib'
import { ns } from 'solid-ui'
import { SocialMutationPlan, SocialRow } from './types'
import { MutationOps, RdfStatement } from '../shared/types'
import { createIdNode } from '../shared/idNodeFactory'
import {
	collectNodeStatements,
	findExistingNode,
	registerStorePrefix,
	runUpdateTransport,
	uniqueStatements
} from '../shared/rdfMutationHelpers'
import { saveSocialUpdatesFailedPrefixText } from '../../texts'
import { findSocialAccountOption, getSocialAccountOptions } from './helpers'
import { presentSocial } from './selectors'
import { expandRdfList } from '../shared/rdfList'
/* The code below for handling reordering were generated by AI Model: GPT-5.3-Codex. */
/* Prompt: can you implement on SocialEditDialog add the bentoIcon as the first item 
on the row, you should be able to drag this button around and it should allow you 
to change the order of the rows and that should change the order in the mutations 
that happen for this data. */

const SOCIAL_ONTOLOGY_NS = 'https://solidos.github.io/profile-pane/src/ontology/socialMedia.ttl#'

function ensureSocialPrefix(store: LiveStore) {
	registerStorePrefix(store, 'soc', SOCIAL_ONTOLOGY_NS)
}

function toObjectNode(value?: string): Node | null {
	const normalized = (value || '').trim()
	if (!normalized) return null
	if (normalized.startsWith('http://') || normalized.startsWith('https://')) {
		return sym(normalized)
	}
	return literal(normalized)
}

function normalizeValue(value?: unknown): string {
	if (typeof value === 'string') return value.trim()
	if (value === null || value === undefined) return ''
	return String(value).trim()
}

function toAccountNameFromHomepage(homepage: string, profilePrefix?: string): string {
	const homepageValue = normalizeValue(homepage)
	if (!homepageValue) return ''

	const prefixValue = normalizeValue(profilePrefix)
	if (prefixValue) {
		let trimmed = homepageValue
		const lowerPrefix = prefixValue.toLowerCase()
		while (trimmed.toLowerCase().startsWith(lowerPrefix)) {
			trimmed = trimmed.slice(prefixValue.length)
		}
		if (trimmed) return trimmed

		try {
			const homepageUrl = new URL(homepageValue)
			const prefixUrl = new URL(prefixValue)
			const normalizeHost = (host: string) => host.toLowerCase().replace(/^www\./, '')
			const homepageHost = normalizeHost(homepageUrl.hostname)
			const prefixHost = normalizeHost(prefixUrl.hostname)
			const prefixPath = (prefixUrl.pathname || '/').replace(/\/+$/, '')
			const homepagePath = homepageUrl.pathname || '/'

			if (homepageHost === prefixHost && homepagePath.startsWith(prefixPath)) {
				const remainder = homepagePath.slice(prefixPath.length).replace(/^\/+/, '')
				if (remainder) return remainder
			}
		} catch {
			// Ignore URL parsing issues and continue to generic normalization.
		}
	}

	return homepageValue
		.replace(/^https?:\/\//i, '')
		.replace(/^www\./i, '')
}

function buildSocialStatements(
	doc: NamedNode,
	node: NamedNode,
	row: SocialRow,
	accountOption?: { classUri: string, label: string, icon: string, userProfilePrefix?: string, homepage?: string }
) {
	const inserts: RdfStatement[] = []
	if (accountOption?.classUri) {
		inserts.push(st(node, ns.rdf('type'), sym(accountOption.classUri), doc))
	}

	const normalizedName = normalizeValue(row.name)
	const isOther = normalizedName.toLowerCase() === 'other' || accountOption?.classUri?.endsWith('#OtherAccount')

	if (isOther) {
		const homepageNode = toObjectNode(row.homepage)
		const iconNode = toObjectNode(row.icon)
		if (homepageNode) inserts.push(st(node, ns.foaf('homepage'), homepageNode, doc))
		if (iconNode) inserts.push(st(node, ns.foaf('icon'), iconNode, doc))
		if (normalizedName && normalizedName.toLowerCase() !== 'other') {
			inserts.push(st(node, ns.rdfs('label'), literal(normalizedName), doc))
		}
		return inserts
	}

	const accountPrefix = accountOption?.userProfilePrefix || accountOption?.homepage
	const accountName = toAccountNameFromHomepage(normalizeValue(row.homepage), accountPrefix)
	if (accountName) {
		inserts.push(st(node, ns.foaf('accountName'), literal(accountName), doc))
	}

	return inserts
}

function buildRdfListStatements(doc: NamedNode, items: NamedNode[]) {
	if (!items.length) {
		return {
			head: ns.rdf('nil') as Node,
			statements: [] as RdfStatement[]
		}
	}

	const listNodes = items.map(() => blankNode())
	const statements: RdfStatement[] = []

	items.forEach((item, index) => {
		const current = listNodes[index]
		const next = listNodes[index + 1] || ns.rdf('nil')
		statements.push(st(current, ns.rdf('first'), item, doc))
		statements.push(st(current, ns.rdf('rest'), next, doc))
	})

	return {
		head: listNodes[0] as Node,
		statements
	}
}

function collectListChainNodes(store: LiveStore, listHead: Node, doc: NamedNode): Node[] {
	if (!store.any(listHead as any, ns.rdf('first'), null, doc)) return []

	const visited = new Set<string>()
	const nodes: Node[] = []
	let current: Node | null = listHead

	while (current) {
		const key = `${current.termType}:${current.value}`
		if (visited.has(key)) break
		visited.add(key)
		nodes.push(current)

		const rest = store.any(current as any, ns.rdf('rest'), null, doc) as Node | null
		if (!rest || (rest.termType === 'NamedNode' && rest.value === ns.rdf('nil').value)) {
			break
		}
		current = rest
	}

	return nodes
}

function mergeSocialOps(existingRows: SocialRow[], socialOps: MutationOps<SocialRow>): SocialRow[] {
	const removeKeys = new Set(
		socialOps.remove
			.map((row) => normalizeValue(row.entryNode))
			.filter(Boolean)
	)

	const updateByKey = new Map(
		socialOps.update
			.map((row) => [normalizeValue(row.entryNode), row] as const)
			.filter(([key]) => Boolean(key))
	)

	const mergedExisting = existingRows
		.filter((row) => !removeKeys.has(normalizeValue(row.entryNode)))
		.map((row) => {
			const key = normalizeValue(row.entryNode)
			return updateByKey.get(key) || row
		})

	const creates = socialOps.create.filter((row) => {
		return Boolean(normalizeValue(row.name) || normalizeValue(row.homepage) || normalizeValue(row.icon))
	})

	return [...mergedExisting, ...creates]
}

function rowsFromOrderedInput(orderedRows: SocialRow[]): SocialRow[] {
	return (orderedRows || [])
		.filter((row) => row.status !== 'deleted')
		.filter((row) => Boolean(normalizeValue(row.name) || normalizeValue(row.homepage) || normalizeValue(row.icon) || normalizeValue(row.entryNode)))
		.map((row) => ({
			name: normalizeValue(row.name),
			icon: normalizeValue(row.icon),
			homepage: normalizeValue(row.homepage),
			entryNode: normalizeValue(row.entryNode),
			status: row.status
		}))
}

async function mutateSocialEntries(
	store: LiveStore,
	subject: NamedNode,
	socialOps: MutationOps<SocialRow>,
	orderedRows?: SocialRow[]
) {
	ensureSocialPrefix(store)
	const doc = subject.doc()
	const accountOptions = getSocialAccountOptions(store)
	const optionForRow = (row: SocialRow) => findSocialAccountOption(accountOptions, normalizeValue(row.name))

	const existingRows: SocialRow[] = presentSocial(subject, store).accounts.map((account) => ({
		name: normalizeValue(account.name),
		icon: normalizeValue(account.icon),
		homepage: normalizeValue(account.homepage),
		entryNode: account.entryNode.value,
		status: 'existing'
	}))

	const nextRows = orderedRows && orderedRows.length
		? rowsFromOrderedInput(orderedRows)
		: mergeSocialOps(existingRows, socialOps)

	const accountObjects = store.each(subject, ns.foaf('account'), null, doc)
	const existingListNodes = uniqueStatements(
		accountObjects.flatMap((objectNode) => {
			return collectListChainNodes(store, objectNode, doc)
				.flatMap((node) => store.statementsMatching(node as any, null, null, doc))
		})
	)

	const existingAccountNodes = Array.from(new Map(
		accountObjects
			.flatMap((objectNode) => expandRdfList(store, objectNode))
			.filter((node) => node.termType === 'NamedNode')
			.map((node) => [`${node.termType}:${node.value}`, node as NamedNode])
	).values())

	const rowEntryNodes = nextRows.map((row) => {
		if (normalizeValue(row.entryNode)) {
			const existing = findExistingNode(existingAccountNodes as Node[], row.entryNode)
			if (existing && existing.termType === 'NamedNode') return existing as NamedNode
		}
		return createIdNode(doc)
	})

	const insertions: RdfStatement[] = []
	if (rowEntryNodes.length > 0) {
		const rdfList = buildRdfListStatements(doc, rowEntryNodes)
		insertions.push(st(subject, ns.foaf('account'), rdfList.head, doc))
		insertions.push(...rdfList.statements)
	}

	nextRows.forEach((row, index) => {
		insertions.push(...buildSocialStatements(doc, rowEntryNodes[index], row, optionForRow(row)))
	})

	const deletions = uniqueStatements([
		...store.statementsMatching(subject, ns.foaf('account'), null, doc),
		...existingListNodes,
		...existingAccountNodes.flatMap((node) => collectNodeStatements(store, node, doc))
	])

	await runUpdateTransport(store, doc, deletions, uniqueStatements(insertions), {
		unsupportedMessage: 'Social updates are not supported by this store updater.',
		failureMessage: 'Failed to save updates',
		useDavFallback: false,
		usePutFallback: true
	})
}

export async function processSocialMutations(
	store: LiveStore,
	subject: NamedNode,
	mutationPlan: SocialMutationPlan,
	orderedRows?: SocialRow[]
) {
	try {
		await mutateSocialEntries(store, subject, mutationPlan, orderedRows)
	} catch (error) {
		const message = error instanceof Error ? error.message : String(error)
		throw new Error(`${saveSocialUpdatesFailedPrefixText} ${message}`)
	}
}
