import { openInputDialog } from '../../ui/dialog'
import { html, render } from 'lit-html'
import type { Account, SocialRow } from './types'
import '../../styles/ContactInfoEditDialog.css'
import '../../styles/EditDialogs.css'
import { LiveStore, NamedNode } from 'rdflib'
import { ViewerMode } from '../../types'
import { applyRowFieldChange, deleteRow, summarizeRowOps } from '../shared/rowState'
import { hasNonEmptyText, sanitizeTextValue, toText } from '../../textUtils'
import { MutationOps } from '../shared/types'
import { processSocialMutations } from './mutations'
import { bentoIcon, trashIcon } from '../../icons-svg/profileIcons'
import {
  deleteEntryButtonTitleText,
  dialogCancelLabelText,
  dialogSubmitLabelText,
  editSocialDialogTitleText,
  ownerLoginRequiredDialogMessageText,
  saveSocialUpdatesFailedPrefixText
} from '../../texts'
import { DEFAULT_ICON_URI } from './constants'
import { findSocialAccountOption, getSocialAccountOptions, type SocialAccountOption } from './helpers'

/* The code below for handling reordering were generated by AI Model: GPT-5.3-Codex. */
/* Prompt: can you implement on SocialEditDialog add the bentoIcon as the first item 
on the row, you should be able to drag this button around and it should allow you 
to change the order of the rows and that should change the order in the mutations 
that happen for this data. */

type SocialFormState = {
  socialAccounts: SocialRow[]
  initialExistingOrder: string[]
}

type SocialEditableField = 'name' | 'icon' | 'homepage'

type SocialRowInputProps = {
  rows: SocialRow[]
  index: number
  displayIndex: number
  onDelete: () => void
  onChange: () => void
  options: SocialAccountOption[]
  onDragStart: (index: number) => void
  onDragOver: (event: DragEvent) => void
  onDrop: (index: number) => void
  onDragEnd: () => void
  isDropTarget: boolean
}

function sanitizeSocialFieldValue(value: string): string {
  return sanitizeTextValue(value)
}

function sanitizeUrlFieldValue(value: string): string {
  return sanitizeTextValue(value).replace(/\s+/g, '')
}

function isValidProfileUrl(value: string): boolean {
  const normalized = (value || '').trim()
  if (!normalized) return false
  try {
    const parsed = new URL(normalized)
    return parsed.protocol === 'http:' || parsed.protocol === 'https:'
  } catch {
    return false
  }
}

function rowHasContent(row: SocialRow): boolean {
  // A social account is considered meaningful only when a personal profile URL is set.
  return hasNonEmptyText(row.homepage)
}

function toFormState(socialAccounts: Account[]): SocialFormState {
  const rows = (socialAccounts || [])
    .map((account) => ({
      name: sanitizeSocialFieldValue(toText(account.name)),
      icon: sanitizeSocialFieldValue(toText(account.icon)),
      homepage: sanitizeSocialFieldValue(toText(account.homepage)),
      entryNode: toText(account.entryNode),
      status: toText(account.entryNode) ? 'existing' as const : 'new' as const
    }))
    .filter((row) => Boolean(row.name || row.icon || row.homepage || row.entryNode))

  return {
    socialAccounts: rows.length
      ? rows
      : [{ name: '', icon: '', homepage: '', entryNode: '', status: 'new' }],
    initialExistingOrder: []
  }
}

function hasOrderChanged(rows: SocialRow[], initialExistingOrder: string[]): boolean {
  const currentExistingOrder = rows
    .filter((row) => row.status !== 'deleted' && Boolean((row.entryNode || '').trim()))
    .map((row) => (row.entryNode || '').trim())

  if (currentExistingOrder.length !== initialExistingOrder.length) return true

  for (let i = 0; i < currentExistingOrder.length; i++) {
    if (currentExistingOrder[i] !== initialExistingOrder[i]) return true
  }

  return false
}

function validateSocialBeforeSave(rows: SocialRow[], initialExistingOrder: string[]): string | null {
  const ops = summarizeRowOps(rows, rowHasContent)
  const hasChanges = ops.create.length > 0 || ops.update.length > 0 || ops.remove.length > 0
  const orderChanged = hasOrderChanged(rows, initialExistingOrder)
  if (!hasChanges && !orderChanged) return 'No social changes detected.'

  for (let i = 0; i < rows.length; i++) {
    const row = rows[i]
    if (!row || row.status === 'deleted') continue

    const hasAnyValue = [row.name, row.icon, row.homepage].some(hasNonEmptyText)
    if (!hasAnyValue) continue

    if (!hasNonEmptyText(row.name) || !hasNonEmptyText(row.icon)) {
      return `Social account ${i + 1}: please choose an account type from the dropdown.`
    }

    if (!hasNonEmptyText(row.homepage)) {
      return `Social account ${i + 1}: please enter your personal profile link.`
    }

    if (!isValidProfileUrl(row.homepage || '')) {
      return `Social account ${i + 1}: profile link must be a valid http(s) URL.`
    }
  }

  return null
}

function renderSocialAccountInputSelect(
  row: SocialRow,
  rowIndex: number,
  options: SocialAccountOption[],
  onChange: (event: Event) => void
) {
  const selected = findSocialAccountOption(options, row?.name || '')
  const selectedLabel = selected?.label || ''

  return html`
    <select
      class="profile-edit-dialog__social-account-select"
      name=${`social-account-type-${rowIndex}`}
      data-row-index=${String(rowIndex)}
      autocomplete="off"
      @change=${onChange}
    >
      <option value="">Select</option>
      ${options.map((option) => html`
        <option value=${option.label} ?selected=${option.label === selectedLabel}>${option.label}</option>
      `)}
    </select>
  `
}

function renderSocialInputRow({
  rows,
  index,
  displayIndex,
  onDelete,
  onChange,
  options,
  onDragStart,
  onDragOver,
  onDrop,
  onDragEnd,
  isDropTarget
}: SocialRowInputProps) {
  const row = rows[index]
  const nameLabel = `Social Account Name ${displayIndex + 1}`
  const homepageLabel = `Social Account Homepage ${displayIndex + 1}`

  const handleTextInput = (field: SocialEditableField) => (event: Event) => {
    const target = event.target as HTMLInputElement
    const nextValue = field === 'homepage'
      ? sanitizeUrlFieldValue(target.value)
      : sanitizeSocialFieldValue(target.value)
    if (rows[index]) {
      applyRowFieldChange(rows[index], field, nextValue, rowHasContent)
      onChange()
    }
  }

  const handleAccountTypeInput = (event: Event) => {
    const target = event.target as HTMLSelectElement
    const selected = findSocialAccountOption(options, target.value)
    if (!rows[index]) return

    if (!selected) {
      applyRowFieldChange(rows[index], 'name', '', rowHasContent)
      applyRowFieldChange(rows[index], 'icon', '', rowHasContent)
      onChange()
      return
    }

    applyRowFieldChange(rows[index], 'name', selected.label, rowHasContent)
    applyRowFieldChange(rows[index], 'icon', selected.icon || DEFAULT_ICON_URI, rowHasContent)

    onChange()
  }

  const handleDelete = (event: Event) => {
    event.preventDefault()
    onDelete()
  }

  return html`
    <div
      class="profile-edit-dialog__row profile-edit-dialog__row--social ${isDropTarget ? 'profile-edit-dialog__row--drop-target' : ''}"
      @dragover=${(event: DragEvent) => onDragOver(event)}
      @drop=${() => onDrop(index)}
    >
      <button
        type="button"
        class="profile-edit-dialog__drag-handle"
        aria-label=${`Reorder social account ${displayIndex + 1}`}
        title="Drag to reorder"
        draggable="true"
        @dragstart=${() => onDragStart(index)}
        @dragend=${() => onDragEnd()}
      >
        ${bentoIcon}
      </button>
     <img 
        class="socialIcon" 
        src="${row?.icon || DEFAULT_ICON_URI}" 
        alt="${row?.name || 'Social'} icon"
        width="30"
        height="30"
        loading="lazy"
      />
      <label aria-label=${nameLabel} class="label profile-edit-dialog__field profile-edit-dialog__field--social-type">
        ${renderSocialAccountInputSelect(row, index, options, handleAccountTypeInput)}
      </label>
      <label aria-label=${homepageLabel} class="label profile-edit-dialog__field profile-edit-dialog__field--social-url">
        <input
          class="input"
          type="url"
          name=${`social-homepage-${index}`}
          .value=${row?.homepage || ''}
          data-contact-field="homepage"
          data-entry-node=${row?.entryNode || ''}
          data-row-status=${row?.status || 'n/a'}
          placeholder="Profile URL"
          autocomplete="url"
          inputmode="url"
          required
          @input=${handleTextInput('homepage')}
        />
        <small class="inputHelpText">Paste your full profile URL (for example: https://example.com/username)</small>
      </label>
      <div class="profile-edit-dialog__actions profile-edit-dialog__actions--edge">
        <button
          type="button"
          class="profile-edit-dialog__delete-button"
          aria-label=${`Delete social account ${displayIndex + 1}`}
          title=${deleteEntryButtonTitleText}
          @click=${handleDelete}
        >
          <span class="profile-edit-dialog__delete-icon" aria-hidden="true">${trashIcon}</span>
        </button>
      </div>
    </div>
  `
}

function renderSocialSection(rows: SocialRow[], options: SocialAccountOption[], onRerender: () => void) {
  let dragSourceIndex: number | null = null
  let dropTargetIndex: number | null = null

  const reorderRows = (from: number, to: number) => {
    if (from === to) return
    const row = rows[from]
    if (!row) return
    rows.splice(from, 1)
    rows.splice(to, 0, row)
  }

  const handleDragStart = (index: number) => {
    dragSourceIndex = index
    dropTargetIndex = index
  }

  const handleDragOver = (event: DragEvent) => {
    event.preventDefault()
    if (event.dataTransfer) {
      event.dataTransfer.dropEffect = 'move'
    }
  }

  const handleDrop = (index: number) => {
    if (dragSourceIndex === null) return
    reorderRows(dragSourceIndex, index)
    dragSourceIndex = null
    dropTargetIndex = null
    onRerender()
  }

  const handleDragEnd = () => {
    dragSourceIndex = null
    dropTargetIndex = null
  }

  const visibleRows = rows
    .map((row, index) => ({ row, index }))
    .filter(({ row }) => row.status !== 'deleted')

  return html`
    <section class="profile-edit-dialog__section" aria-label="Social Accounts">
      <fieldset>
        <legend class="sr-only">Social account entries</legend>
        ${visibleRows.map(({ index }, displayIndex) =>
          renderSocialInputRow({
            rows,
            index,
            displayIndex,
            onDelete: () => {
              deleteRow(rows, index)
              onRerender()
            },
            onChange: onRerender,
            options,
            onDragStart: handleDragStart,
            onDragOver: handleDragOver,
            onDrop: handleDrop,
            onDragEnd: handleDragEnd,
            isDropTarget: dropTargetIndex === index
          })
        )}
      </fieldset>
    </section>
  `
}

function renderSocialEditTemplate(
  form: HTMLFormElement,
  formState: SocialFormState,
  store: LiveStore,
  viewerMode: ViewerMode
) {
  const rerender = () => renderSocialEditTemplate(form, formState, store, viewerMode)
  const options = getSocialAccountOptions(store)
  render(html`
    ${renderSocialSection(formState.socialAccounts, options, rerender)}
    ${viewerMode !== 'owner'
      ? html`<p class="profile-edit-dialog__login-message">${ownerLoginRequiredDialogMessageText}</p>`
      : null}
  `, form)
}

function createSocialEditForm(details: Account[], store: LiveStore, viewerMode: ViewerMode) {
  const form = document.createElement('form')
  form.classList.add('profile__edit-form')

  const formState = toFormState(details)
  formState.initialExistingOrder = formState.socialAccounts
    .filter((row) => Boolean((row.entryNode || '').trim()))
    .map((row) => (row.entryNode || '').trim())
  renderSocialEditTemplate(form, formState, store, viewerMode)

  const addRow = () => {
    formState.socialAccounts.push({
      name: '',
      icon: '',
      homepage: '',
      entryNode: '',
      status: 'new'
    })
    renderSocialEditTemplate(form, formState, store, viewerMode)
  }

  return { form, formState, addRow }
}

export async function createSocialEditDialog(
  event: Event,
  store: LiveStore,
  subject: NamedNode,
  socialAccounts: Account[],
  viewerMode: ViewerMode,
  onSaved?: () => Promise<void> | void
) {
  const dom = (event.currentTarget as HTMLElement | null)?.ownerDocument || document
  const { form, formState, addRow } = createSocialEditForm(socialAccounts, store, viewerMode)

  const result = await openInputDialog({
    title: editSocialDialogTitleText,
    dom,
    form,
    headerAction: {
      type: 'button',
      label: '+ Add More',
      ariaLabel: 'Add another social account',
      onClick: addRow
    },
    submitLabel: dialogSubmitLabelText,
    cancelLabel: dialogCancelLabelText,
    validate: () => {
      if (viewerMode !== 'owner') {
        return ownerLoginRequiredDialogMessageText
      }
      return validateSocialBeforeSave(formState.socialAccounts, formState.initialExistingOrder)
    },
    onSave: async () => {
      const socialOps = summarizeRowOps(formState.socialAccounts, rowHasContent)
      const plan: MutationOps<SocialRow> = {
        create: socialOps.create,
        update: socialOps.update,
        remove: socialOps.remove
      }
      await processSocialMutations(store, subject, plan, formState.socialAccounts)
    },
    formatSaveError: (error: unknown) => {
      const message = error instanceof Error ? error.message : String(error)
      return message.startsWith(saveSocialUpdatesFailedPrefixText)
        ? message
        : `${saveSocialUpdatesFailedPrefixText} ${message}`
    }
  })

  if (!result) return

  if (onSaved) {
    await onSaved()
  }
}
