import { alertDialog, openInputDialog } from "../../ui/dialog"
import { html, render } from "lit-html"
import { ContactAddressRow, ContactInfo, ContactMutationPlan, ContactPointRow } from "./types"
import "../../styles/ContactInfoEditDialog.css"
import { LiveStore, NamedNode } from "rdflib"
import { processContactInfoMutations } from "./mutations"
import { ViewerMode } from "../../types"
import {
  combinePhoneValue,
  COUNTRY_PREFIX_OPTIONS,
  countryCodeToFlag,
  splitPhoneValue
} from "./phoneCountries"

/* Some of the code in this file was generated by AI Model: GPT-5.3-Codex  */
/* Prompt: 1. are you able to create a little trash can icon at the end of 
              each entry so for each phone, email and address line.
           2. are you able to add all the country flags and prefix next to 
              the phone numbers? 
           3. can you write functions to sanitize the input values for emails, phones, and addresses? */

type ContactInfoFormState = {
  emails: ContactPointRow[]
  phones: ContactPointRow[]
  addresses: ContactAddressRow[]
}

function toText(value: unknown): string {
  if (!value) return ''
  if (typeof value === 'string') return value
  if (typeof value === 'object' && 'value' in (value as Record<string, unknown>)) {
    const v = (value as { value?: unknown }).value
    return typeof v === 'string' ? v : ''
  }
  return ''
}

function toTypeLabel(value: unknown): string {
  const raw = toText(value).trim()
  if (!raw) return ''
  const withoutAngles = raw.replace(/^<|>$/g, '')
  const hashParts = withoutAngles.split('#')
  const lastByHash = hashParts[hashParts.length - 1]
  const slashParts = lastByHash.split('/')
  return slashParts[slashParts.length - 1]
}

function sanitizeTextValue(value: string): string {
  return value
    .replace(/[\u0000-\u001F\u007F]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()
}

function sanitizeEmailValue(value: string): string {
  return sanitizeTextValue(value).replace(/\s+/g, '').toLowerCase()
}

function sanitizePhoneLocalValue(value: string): string {
  return sanitizeTextValue(value).replace(/[^0-9()\-\s.]/g, '')
}

function sanitizeAddressFieldValue(value: string): string {
  return sanitizeTextValue(value)
}

/* The following 3 functions were generated by AI Model: GPT-5.3-Codex  */
/* Prompt: can you have summarizeRowOps check all fields of address */
function hasNonEmptyText(value: string | undefined): boolean {
  return Boolean(value && value.trim() !== '')
}

function isContactPointRow(row: ContactPointRow | ContactAddressRow): row is ContactPointRow {
  return 'value' in row
}

function rowHasContent(row: ContactPointRow | ContactAddressRow): boolean {
  if (isContactPointRow(row)) {
    return hasNonEmptyText(row.value)
  }

  return [
    row.streetAddress,
    row.locality,
    row.region,
    row.postalCode,
    row.countryName
  ].some(hasNonEmptyText)
}

function toFormState(contactInfo: ContactInfo): ContactInfoFormState {
  const emails = (contactInfo.emails || [])
    .map((email) => ({
      value: sanitizeEmailValue(toText(email.valueNode).replace(/^mailto:/i, '')),
      type: toTypeLabel(email.type),
      entryNode: toText(email.entryNode),
      status: toText(email.entryNode) ? 'existing' as const : 'new' as const
    }))
    .filter((email) => Boolean(email.value || email.entryNode || email.type))

  const phones = (contactInfo.phones || [])
    .map((phone) => ({
      value: sanitizeTextValue(toText(phone.valueNode).replace(/^tel:/i, '')),
      type: toTypeLabel(phone.type),
      entryNode: toText(phone.entryNode),
      status: 'existing' as const
    }))
    .filter((phone) => Boolean(phone.value))
  const addresses = (contactInfo.addresses || [])
    .map((address) => ({
      streetAddress: sanitizeAddressFieldValue(toText(address.streetAddress)),
      locality: sanitizeAddressFieldValue(toText(address.locality)),
      region: sanitizeAddressFieldValue(toText(address.region)),
      postalCode: sanitizeAddressFieldValue(toText(address.postalCode)),
      countryName: sanitizeAddressFieldValue(toText(address.countryName)),
      type: toTypeLabel(address.type),
      entryNode: toText(address.entryNode),
      status: toText(address.entryNode) ? 'existing' as const : 'new' as const
    }))
    .filter((address) => rowHasContent(address) || Boolean(address.entryNode || address.type))

  return {
    emails: emails.length ? emails : [{ value: '', type: '', entryNode: '', status: 'new' }],
    phones: phones.length ? phones : [{ value: '', type: '', entryNode: '', status: 'new' }],
    addresses: addresses.length
      ? addresses
      : [{ streetAddress: '', locality: '', region: '', postalCode: '', countryName: '', type: '', entryNode: '', status: 'new' }]
  }
}

function summarizeRowOps<T extends ContactPointRow | ContactAddressRow>(rows: T[]) {
  const create = rows.filter((row) => row.status === 'new' && rowHasContent(row))
  const update = rows.filter((row) => row.status === 'modified' && rowHasContent(row))
  const remove = rows.filter((row) => row.status === 'deleted')
  return { create, update, remove }
}

function applyPointRowValueChange(row: ContactPointRow, nextValue: string) {
  const trimmed = nextValue.trim()

  if (trimmed === '') {
    row.value = ''
    row.status = row.entryNode ? 'deleted' : 'new'
    return
  }

  row.value = nextValue

  if (row.entryNode) {
    row.status = row.status === 'existing' || row.status === 'deleted' ? 'modified' : row.status
    return
  }

  row.status = 'new'
}

function applyRowTypeChange(row: ContactPointRow | ContactAddressRow, nextValue: string) {
  row.type = nextValue.trim()

  if (row.entryNode) {
    row.status = row.status === 'existing' || row.status === 'deleted' ? 'modified' : row.status
    return
  }

  row.status = 'new'
}

type ContactAddressEditableField =
  | 'streetAddress'
  | 'locality'
  | 'region'
  | 'postalCode'
  | 'countryName'

/* The following function was generated by AI Model: GPT-5.3-Codex  */
/* Prompt: can you have applyAddressFieldChange update the row status based on whether any fields have content */  
function applyAddressFieldChange(
  row: ContactAddressRow,
  field: ContactAddressEditableField,
  nextValue: string
) {
  row[field] = nextValue

  if (!rowHasContent(row)) {
    row.status = row.entryNode ? 'deleted' : 'new'
    return
  }

  if (row.entryNode) {
    row.status = row.status === 'existing' || row.status === 'deleted' ? 'modified' : row.status
    return
  }

  row.status = 'new'
}

type ContactPhoneInputRowProps = {
  phones: ContactPointRow[]
  index: number
  displayIndex: number
  onDelete: () => void
}

type ContactEmailInputRowProps = {
  emails: ContactPointRow[]
  index: number
  displayIndex: number
  onDelete: () => void
}

type ContactAddressInputRowProps = {
  addresses: ContactAddressRow[]
  index: number
  displayIndex: number
  onDelete: () => void
}

function deleteRow<T extends ContactPointRow | ContactAddressRow>(rows: T[], index: number) {
  const row = rows[index]
  if (!row) return

  if (row.entryNode) {
    row.status = 'deleted'
    return
  }

  rows.splice(index, 1)
}
function renderCountryPrefixSelect(
  name: string,
  value: string,
  label: string,
  onChange: (event: Event) => void
) {
  return html`
    <label class="phonePrefixField" aria-label=${label}>
      <select class="phonePrefixSelect" name=${name} .value=${value} @change=${onChange}>
        ${COUNTRY_PREFIX_OPTIONS.map((option) => html`
          <option value=${option.dialCode}>
            ${countryCodeToFlag(option.iso2)} ${option.dialCode}
          </option>
        `)}
      </select>
    </label>
  `
}

function renderContactPhoneInputRow({
  phones,
  index,
  displayIndex,
  onDelete
}: ContactPhoneInputRowProps) {
  const phoneRow = phones[index]
  const label = `Phone Number ${displayIndex + 1}`
  const countryCodeLabel = `Country Calling Code ${displayIndex + 1}`
  const typeLabel = `Phone Type ${displayIndex + 1}`
  const prefixInputName = `phone-prefix-${index}`
  const inputName = `phone-value-${index}`
  const typeInputName = `phone-type-${index}`
  const splitValue = splitPhoneValue(phoneRow?.value || '')
  let selectedDialCode = splitValue.dialCode

  const handleValueInput = (e: Event) => {
    const target = e.target as HTMLInputElement
    const nextValue = sanitizePhoneLocalValue(target.value)
    if (phones[index]) {
      applyPointRowValueChange(phones[index], combinePhoneValue(selectedDialCode, nextValue))
    }
  }

  const handleCountryCodeInput = (e: Event) => {
    const target = e.target as HTMLSelectElement
    selectedDialCode = target.value

    if (phones[index]) {
      const localNumber = splitPhoneValue(phones[index].value).localNumber
      applyPointRowValueChange(phones[index], combinePhoneValue(selectedDialCode, localNumber))
    }
  }

  const handleTypeInput = (e: Event) => {
    const target = e.target as HTMLInputElement
    const nextType = target.value
    if (phones[index]) {
      applyRowTypeChange(phones[index], nextType)
    }
  }

  const handleDelete = (event: Event) => {
    event.preventDefault()
    onDelete()
  }

  return html`
    <div class="contactInputRow">
      <div class="contactInputValueRow phoneCompositeRow">
        ${renderCountryPrefixSelect(prefixInputName, selectedDialCode, countryCodeLabel, handleCountryCodeInput)}
        <span class="phoneCompositeDivider" aria-hidden="true">|</span>
        <label aria-label=${label} class="phoneLocalField">
          <input
            class="phoneLocalInput"
            type="tel"
            name=${inputName}
            .value=${splitValue.localNumber}
            data-contact-field="value"
            data-entry-node=${phoneRow?.entryNode || ''}
            data-row-status=${phoneRow?.status || 'n/a'}
            placeholder="Phone Number"
            autocomplete="tel-national"
            inputmode="tel"
            @input=${handleValueInput}
          />
        </label>
      </div>
      <label aria-label=${typeLabel} class="contactInputTypeRow phoneTypeRow">
        <select name=${typeInputName} id="phone-type-select-${inputName}" @change=${handleTypeInput} .value=${phoneRow?.type || ''}>
          <option value="Home">Mobile</option>
          <option value="Home">Home</option>
          <option value="Work">Work</option>
          <option value="Other">Other</option>
        </select>
      </label>
      <div class="contactInputActions">
        <button
          type="button"
          class="deleteEntryButton"
          aria-label=${`Delete phone number ${displayIndex + 1}`}
          title="Delete entry"
          @click=${handleDelete}
        >
          <svg class="deleteEntryIcon" viewBox="0 0 24 24" aria-hidden="true" focusable="false">
            <path d="M9 3h6l1 2h4v2H4V5h4l1-2zm-1 6h2v9H8V9zm6 0h2v9h-2V9zM6 9h12l-1 12H7L6 9z" />
          </svg>
        </button>
      </div>
    </div>
  `
}

function renderContactInfoPhoneSection(phones: ContactPointRow[], onAddRow: () => void) {
  const createNewRow = (event: Event) => {
    event.preventDefault()
    phones.push({ value: '', type: '', entryNode: '', status: 'new' })
    onAddRow()
  }

  const visiblePhones = phones
    .map((phone, index) => ({ phone, index }))
    .filter(({ phone }) => phone.status !== 'deleted')

  return html`
    <section 
      aria-labelledby="phone-numbers-heading" 
      class="contactsEditSection section-bg">
      <header class="sectionHeader">
        <h4 id="phone-numbers-heading" tabindex="-1">
          <span class="sectionTitleIcon" aria-hidden="true">&#9742;</span>
          Phone Numbers
        </h4>
        <button
          type="button"
          class="actionButton"
          aria-label="Add another phone number"
          @click=${createNewRow}
        >
          + Add More
        </button>
      </header>
      <fieldset>
        <legend class="sr-only">Phone number entries</legend>
        ${visiblePhones.map(({ index }, displayIndex) => renderContactPhoneInputRow({
          phones,
          index,
          displayIndex,
          onDelete: () => {
            deleteRow(phones, index)
            onAddRow()
          }
        }))}
      </fieldset>
    </section>
  `
}

function renderContactEmailInputRow({
  emails,
  index,
  displayIndex,
  onDelete
}: ContactEmailInputRowProps) {
  const emailRow = emails[index]
  const label = `Email Address ${displayIndex + 1}`
  const typeLabel = `Email Type ${displayIndex + 1}`
  const inputName = `email-value-${index}`
  const typeInputName = `email-type-${index}`

  const handleValueInput = (e: Event) => {
    const target = e.target as HTMLInputElement
    const nextValue = sanitizeEmailValue(target.value)
    if (emails[index]) {
      applyPointRowValueChange(emails[index], nextValue)
    }
  }

  const handleTypeInput = (e: Event) => {
    const target = e.target as HTMLInputElement
    const nextType = target.value
    if (emails[index]) {
      applyRowTypeChange(emails[index], nextType)
    }
  }

  const handleDelete = (event: Event) => {
    event.preventDefault()
    onDelete()
  }

  return html`
    <div class="contactInputRow">
      <label aria-label=${label} class="contactInputValueRow">
        <input
          type="email"
          name=${inputName}
          .value=${emailRow?.value || ''}
          data-contact-field="value"
          data-entry-node=${emailRow?.entryNode || ''}
          data-row-status=${emailRow?.status || 'n/a'}
          placeholder="Email Address"
          autocomplete="email"
          inputmode="email"
          @input=${handleValueInput}
        />
      </label>
      <label aria-label=${typeLabel} class="contactInputTypeRow">
        <select name=${typeInputName} id="email-type-select-${inputName}" @change=${handleTypeInput} .value=${emailRow?.type || ''}>
          <option value="Personal">Personal</option>
          <option value="Office">Office</option>
          <option value="Other">Other</option>
        </select>
      </label>
      <div class="contactInputActions">
        <button
          type="button"
          class="deleteEntryButton"
          aria-label=${`Delete email address ${displayIndex + 1}`}
          title="Delete entry"
          @click=${handleDelete}
        >
          <svg class="deleteEntryIcon" viewBox="0 0 24 24" aria-hidden="true" focusable="false">
            <path d="M9 3h6l1 2h4v2H4V5h4l1-2zm-1 6h2v9H8V9zm6 0h2v9h-2V9zM6 9h12l-1 12H7L6 9z" />
          </svg>
        </button>
      </div>
    </div>
  `
}

function renderContactInfoEmailSection(emails: ContactPointRow[], onAddRow: () => void) {
  const createNewRow = (event: Event) => {
    event.preventDefault()
    emails.push({ value: '', type: '', entryNode: '', status: 'new' })
    onAddRow()
  }

  const visibleEmails = emails
    .map((email, index) => ({ email, index }))
    .filter(({ email }) => email.status !== 'deleted')

  return html`
    <section 
      aria-labelledby="email-addresses-heading" 
      class="contactsEditSection section-bg">
      <header class="sectionHeader">
        <h4 id="email-addresses-heading" tabindex="-1">
          <span class="sectionTitleIcon" aria-hidden="true">&#9993;</span>
          Email Addresses
        </h4>
        <button
          type="button"
          class="actionButton"
          aria-label="Add another email address"
          @click=${createNewRow}
        >
          + Add More
        </button>
      </header>
      <fieldset>
        <legend class="sr-only">Email address entries</legend>
        ${visibleEmails.map(({ index }, displayIndex) => renderContactEmailInputRow({
          emails,
          index,
          displayIndex,
          onDelete: () => {
            deleteRow(emails, index)
            onAddRow()
          }
        }))}
      </fieldset>
    </section>
  `
}

function renderContactAddressInputRow({
  addresses,
  index,
  displayIndex,
  onDelete
}: ContactAddressInputRowProps) {
  const addressRow = addresses[index]
  const label = `Address ${displayIndex + 1}`
  const typeLabel = `Address Type ${displayIndex + 1}`
  const streetAddressName = `address-street-${index}`
  const localityName = `address-locality-${index}`
  const regionName = `address-region-${index}`
  const postalCodeName = `address-postal-${index}`
  const countryName = `address-country-${index}`
  const typeInputName = `address-type-${index}`
  const addressTypeSelectId = `address-type-select-${index}`

  const handleAddressInput = (field: ContactAddressEditableField) => (e: Event) => {
    const target = e.target as HTMLInputElement
    const nextValue = sanitizeAddressFieldValue(target.value)
    if (addresses[index]) {
      applyAddressFieldChange(addresses[index], field, nextValue)
    }
  }

  const handleTypeInput = (e: Event) => {
    const target = e.target as HTMLInputElement
    const nextType = target.value
    if (addresses[index]) {
      applyRowTypeChange(addresses[index], nextType)
    }
  }

  const handleDelete = (event: Event) => {
    event.preventDefault()
    onDelete()
  }

  return html`
    <div class="contactInputRow contactInputRow--addressHeader">
      <label aria-label=${typeLabel} class="contactInputTypeRow contactInputTypeRow--wide">
        Address Type
        <select name=${typeInputName} id=${addressTypeSelectId} @change=${handleTypeInput} .value=${addressRow?.type || ''}>
          <option value="Home">Home</option>
          <option value="Work">Work</option>
          <option value="Other">Other</option>
        </select>
      </label>
      <div class="contactInputActions contactInputActions--edge">
        <button
          type="button"
          class="deleteEntryButton"
          aria-label=${`Delete address ${displayIndex + 1}`}
          title="Delete entry"
          @click=${handleDelete}
        >
          <svg class="deleteEntryIcon" viewBox="0 0 24 24" aria-hidden="true" focusable="false">
            <path d="M9 3h6l1 2h4v2H4V5h4l1-2zm-1 6h2v9H8V9zm6 0h2v9h-2V9zM6 9h12l-1 12H7L6 9z" />
          </svg>
        </button>
      </div>
    </div>
    <label aria-label=${`${label} Street`} class="contactInputValueRow">
      Street Address
      <input
        type="text"
        name=${streetAddressName}
        .value=${addressRow?.streetAddress || ''}
        data-contact-field="streetAddress"
        data-entry-node=${addressRow?.entryNode || ''}
        data-row-status=${addressRow?.status || 'n/a'}
        placeholder="Street Address"
        autocomplete="street-address"
        inputmode="text"
        @change=${handleAddressInput('streetAddress')}
      />
    </label>

    <div class="contactInputRow">
      <label aria-label=${`${label} Locality`} class="contactInputValueRow">
        Locality
        <input
          type="text"
          name=${localityName}
          .value=${addressRow?.locality || ''}
          data-contact-field="locality"
          data-entry-node=${addressRow?.entryNode || ''}
          data-row-status=${addressRow?.status || 'n/a'}
          placeholder="City / Locality"
          autocomplete="address-level2"
          inputmode="text"
          @change=${handleAddressInput('locality')}
        />
      </label>
      <label aria-label=${`${label} Postal Code`} class="contactInputValueRow">
        Postal Code
        <input
          type="text"
          name=${postalCodeName}
          .value=${addressRow?.postalCode || ''}
          data-contact-field="postalCode"
          data-entry-node=${addressRow?.entryNode || ''}
          data-row-status=${addressRow?.status || 'n/a'}
          placeholder="Postal Code"
          autocomplete="postal-code"
          inputmode="text"
          @change=${handleAddressInput('postalCode')}
        />
      </label>
    </div>

    <div class="contactInputRow">
      <label aria-label=${`${label} Region`} class="contactInputValueRow">
        Region
        <input
          type="text"
          name=${regionName}
          .value=${addressRow?.region || ''}
          data-contact-field="region"
          data-entry-node=${addressRow?.entryNode || ''}
          data-row-status=${addressRow?.status || 'n/a'}
          placeholder="State / Region"
          autocomplete="address-level1"
          inputmode="text"
          @change=${handleAddressInput('region')}
        />
      </label>
      <label aria-label=${`${label} Country`} class="contactInputValueRow">
        Country
        <input
          type="text"
          name=${countryName}
          .value=${addressRow?.countryName || ''}
          data-contact-field="countryName"
          data-entry-node=${addressRow?.entryNode || ''}
          data-row-status=${addressRow?.status || 'n/a'}
          placeholder="Country"
          autocomplete="country-name"
          inputmode="text"
          @change=${handleAddressInput('countryName')}
        />
      </label>
    </div>
  `
}

function renderContactInfoAddressSection(addresses: ContactAddressRow[], onAddRow: () => void) {
  const createNewRow = (event: Event) => {
    event.preventDefault()
    addresses.push({
      streetAddress: '',
      locality: '',
      region: '',
      postalCode: '',
      countryName: '',
      type: '',
      entryNode: '',
      status: 'new'
    })
    onAddRow()
  }

  const visibleAddresses = addresses
    .map((address, index) => ({ address, index }))
    .filter(({ address }) => address.status !== 'deleted')

  return html`
    <section 
      aria-labelledby="address-heading" 
      class="contactsEditSection section-bg">
      <header class="sectionHeader">
        <h4 id="address-heading" tabindex="-1">
          <span class="sectionTitleIcon" aria-hidden="true">&#9993;</span>
          Addresses
        </h4>
        <button
          type="button"
          class="actionButton"
          aria-label="Add another address"
          @click=${createNewRow}
        >
          + Add More
        </button>
      </header>
      <fieldset>
        <legend class="sr-only">Address entries</legend>
        ${visibleAddresses.map(({ index }, displayIndex) => renderContactAddressInputRow({
          addresses,
          index,
          displayIndex,
          onDelete: () => {
            deleteRow(addresses, index)
            onAddRow()
          }
        }))}
      </fieldset>
    </section>
  `
}

function renderContactInfoEditTemplate(form: HTMLFormElement, formState: ContactInfoFormState) {
  const rerender = () => renderContactInfoEditTemplate(form, formState)


  render(html`
    ${renderContactInfoPhoneSection(formState.phones, rerender)}
    ${renderContactInfoEmailSection(formState.emails, rerender)}
    ${renderContactInfoAddressSection(formState.addresses, rerender)}
  `, form)
}

function createContactInfoEditForm(contactInfo: ContactInfo) {
  const form = document.createElement('form')
  form.classList.add('section-edit-form')

  const formState = toFormState(contactInfo)
  renderContactInfoEditTemplate(form, formState)

  return { form, formState }
}


export async function createContactInfoEditDialog(
  event: Event,
  store: LiveStore,
  subject: NamedNode,
  contactInfo: ContactInfo,
  viewerMode: ViewerMode
) {
  const dom = (event.currentTarget as HTMLElement | null)?.ownerDocument || document
  const { form, formState } = createContactInfoEditForm(contactInfo)

  const result = await openInputDialog({
    title: 'Edit More Contacts',
    dom,
    form,
    submitLabel: 'Save Changes',
    cancelLabel: 'Cancel'
  })

  if (!result) return

  if (viewerMode !== 'owner') {
    await alertDialog('You need to log in as the profile owner to save contact updates.', 'Login Required', dom)
    return
  }

 const plan: ContactMutationPlan = {
  phoneOps: summarizeRowOps(formState.phones),
  emailOps: summarizeRowOps(formState.emails),
  addressOps: summarizeRowOps(formState.addresses)
}

  // Save wiring is section-specific and can be added when mutation logic is ready.
  console.log('Contact edit values', result)
  console.log('Pending phone operations', plan.phoneOps)
  console.log('Pending email operations', plan.emailOps)
  console.log('Pending address operations', plan.addressOps)

  try {
    await processContactInfoMutations(store, subject, plan)

    const view = dom.defaultView
    if (view) {
      view.location.reload()
    }
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error)
    await alertDialog(`Could not save contact updates. ${message}`, 'Save Failed', dom)
  }
}

