import { openInputDialog } from '../../ui/dialog'
import { html, render } from 'lit-html'
import { ContactAddressRow, ContactInfo, ContactMutationPlan, ContactPointRow } from './types'
import '../../styles/EditDialogs.css'
import '../../styles/ContactInfoEditDialog.css'
import { LiveStore, NamedNode } from 'rdflib'
import { processContactInfoMutations } from './mutations'
import { ViewerMode } from '../../types'
import {
  combinePhoneValue,
  COUNTRY_PREFIX_OPTIONS,
  countryCodeToFlag,
  splitPhoneValue
} from '../shared/phoneCountries'
import { applyRowFieldChange, applyRowSelectChange, deleteRow, summarizeRowOps } from '../shared/rowState'
import { hasNonEmptyText, sanitizeTextValue, toText, toTypeLabel } from '../../textUtils'
import {
  deleteEntryButtonTitleText,
  dialogCancelLabelText,
  dialogSubmitLabelText,
  editContactInfoDialogTitleText,
  ownerLoginRequiredDialogMessageText,
  saveContactUpdatesFailedPrefixText
} from '../../texts'
import { sanitizeAddressFieldValue, sanitizeEmailValue, sanitizePhoneLocalValue } from '../shared/sanitizeUtils'
import { addIcon } from '../../icons-svg/profileIcons'

/* Some of the code in this file was generated by AI Model: GPT-5.3-Codex  */
/* Prompt: 1. are you able to create a little trash can icon at the end of 
              each entry so for each phone, email and address line.
           2. are you able to add all the country flags and prefix next to 
              the phone numbers? 
           3. can you write functions to sanitize the input values for emails, phones, and addresses? */

type ContactInfoFormState = {
  emails: ContactPointRow[]
  phones: ContactPointRow[]
  addresses: ContactAddressRow[]
}

function isContactPointRow(row: ContactPointRow | ContactAddressRow): row is ContactPointRow {
  return 'value' in row
}

function rowHasContent(row: ContactPointRow | ContactAddressRow): boolean {
  if (isContactPointRow(row)) {
    return hasNonEmptyText(row.value)
  }

  return [
    row.streetAddress,
    row.locality,
    row.region,
    row.postalCode,
    row.countryName
  ].some(hasNonEmptyText)
}

function toFormState(contactInfo: ContactInfo): ContactInfoFormState {
  const emails = (contactInfo.emails || [])
    .map((email) => ({
      value: sanitizeEmailValue(toText(email.valueNode).replace(/^mailto:/i, '')),
      type: toTypeLabel(email.type),
      entryNode: toText(email.entryNode),
      status: toText(email.entryNode) ? 'existing' as const : 'new' as const
    }))
    .filter((email) => Boolean(email.value || email.entryNode || email.type))

  const phones = (contactInfo.phones || [])
    .map((phone) => ({
      value: sanitizeTextValue(toText(phone.valueNode).replace(/^tel:/i, '')),
      type: toTypeLabel(phone.type),
      entryNode: toText(phone.entryNode),
      status: 'existing' as const
    }))
    .filter((phone) => Boolean(phone.value))
  const addresses = (contactInfo.addresses || [])
    .map((address) => ({
      streetAddress: sanitizeAddressFieldValue(toText(address.streetAddress)),
      locality: sanitizeAddressFieldValue(toText(address.locality)),
      region: sanitizeAddressFieldValue(toText(address.region)),
      postalCode: sanitizeAddressFieldValue(toText(address.postalCode)),
      countryName: sanitizeAddressFieldValue(toText(address.countryName)),
      type: toTypeLabel(address.type),
      entryNode: toText(address.entryNode),
      status: toText(address.entryNode) ? 'existing' as const : 'new' as const
    }))
    .filter((address) => rowHasContent(address) || Boolean(address.entryNode || address.type))

  return {
    emails: emails.length ? emails : [{ value: '', type: '', entryNode: '', status: 'new' }],
    phones: phones.length ? phones : [{ value: '', type: '', entryNode: '', status: 'new' }],
    addresses: addresses.length
      ? addresses
      : [{ streetAddress: '', locality: '', region: '', postalCode: '', countryName: '', type: '', entryNode: '', status: 'new' }]
  }
}

type ContactAddressEditableField =
  | 'streetAddress'
  | 'locality'
  | 'region'
  | 'postalCode'
  | 'countryName'

type ContactPhoneInputRowProps = {
  phones: ContactPointRow[]
  index: number
  displayIndex: number
  onDelete: () => void
}

type ContactEmailInputRowProps = {
  emails: ContactPointRow[]
  index: number
  displayIndex: number
  onDelete: () => void
}

type ContactAddressInputRowProps = {
  addresses: ContactAddressRow[]
  index: number
  displayIndex: number
  onDelete: () => void
}

function renderCountryPrefixSelect(
  name: string,
  value: string,
  label: string,
  onChange: (event: Event) => void
) {
  return html`
    <label class="label phonePrefixField" aria-label=${label}>
      <select class="phonePrefixSelect" name=${name} .value=${value} @change=${onChange}>
        ${COUNTRY_PREFIX_OPTIONS.map((option) => html`
          <option value=${option.dialCode}>
            ${countryCodeToFlag(option.iso2)} ${option.dialCode}
          </option>
        `)}
      </select>
    </label>
  `
}

function renderContactPhoneInputRow({
  phones,
  index,
  displayIndex,
  onDelete
}: ContactPhoneInputRowProps) {
  const phoneRow = phones[index]
  const label = `Phone Number ${displayIndex + 1}`
  const countryCodeLabel = `Country Calling Code ${displayIndex + 1}`
  const typeLabel = `Phone Type ${displayIndex + 1}`
  const prefixInputName = `phone-prefix-${index}`
  const inputName = `phone-value-${index}`
  const typeInputName = `phone-type-${index}`
  const splitValue = splitPhoneValue(phoneRow?.value || '')
  let selectedDialCode = splitValue.dialCode

  const handleValueInput = (e: Event) => {
    const target = e.target as HTMLInputElement
    const nextValue = sanitizePhoneLocalValue(target.value)
    if (phones[index]) {
      applyRowFieldChange(phones[index], 'value', combinePhoneValue(selectedDialCode, nextValue), rowHasContent)
    }
  }

  const handleCountryCodeInput = (e: Event) => {
    const target = e.target as HTMLSelectElement
    selectedDialCode = target.value

    if (phones[index]) {
      const localNumber = splitPhoneValue(phones[index].value).localNumber
      applyRowFieldChange(phones[index], 'value', combinePhoneValue(selectedDialCode, localNumber), rowHasContent)
    }
  }

  const handleTypeInput = (e: Event) => {
    const target = e.target as HTMLSelectElement
    const nextType = target.value
    if (phones[index]) {
      applyRowSelectChange(phones[index], 'type', nextType)
    }
  }

  const handleDelete = (event: Event) => {
    event.preventDefault()
    onDelete()
  }

  return html`
    <div class="profile-edit-dialog__row">
      <div class="profile-edit-dialog__field phoneCompositeRow">
        ${renderCountryPrefixSelect(prefixInputName, selectedDialCode, countryCodeLabel, handleCountryCodeInput)}
        <span class="phoneCompositeDivider" aria-hidden="true">|</span>
        <label aria-label=${label} class="label phoneLocalField">
          <input
            class="phoneLocalInput input"
            type="tel"
            name=${inputName}
            .value=${splitValue.localNumber}
            required
            data-contact-field="value"
            data-entry-node=${phoneRow?.entryNode || ''}
            data-row-status=${phoneRow?.status || 'n/a'}
            placeholder="Phone Number"
            autocomplete="tel-national"
            inputmode="tel"
            @input=${handleValueInput}
          />
        </label>
      </div>
      <label aria-label=${typeLabel} class="label profile-edit-dialog__field-type phoneTypeRow">
        <select name=${typeInputName} id="phone-type-select-${inputName}" @change=${handleTypeInput} .value=${phoneRow?.type || ''}>
          <option value="Home">Mobile</option>
          <option value="Home">Home</option>
          <option value="Work">Work</option>
          <option value="Other">Other</option>
        </select>
      </label>
      <div class="inputActions">
        <button
          type="button"
          class="deleteEntryButton"
          aria-label=${`Delete phone number ${displayIndex + 1}`}
          title=${deleteEntryButtonTitleText}
          @click=${handleDelete}
        >
          <svg class="deleteEntryIcon" viewBox="0 0 24 24" aria-hidden="true" focusable="false">
            <path d="M9 3h6l1 2h4v2H4V5h4l1-2zm-1 6h2v9H8V9zm6 0h2v9h-2V9zM6 9h12l-1 12H7L6 9z" />
          </svg>
        </button>
      </div>
    </div>
  `
}

function renderContactInfoPhoneSection(phones: ContactPointRow[], onAddRow: () => void) {
  const createNewRow = (event: Event) => {
    event.preventDefault()
    phones.push({ value: '', type: '', entryNode: '', status: 'new' })
    onAddRow()
  }

  const visiblePhones = phones
    .map((phone, index) => ({ phone, index }))
    .filter(({ phone }) => phone.status !== 'deleted')

  return html`
    <section 
      aria-labelledby="phone-numbers-heading" 
      class="contactsEditSection section-bg">
      <header class="profile__section-header">
        <h4 id="phone-numbers-heading">
          <span class="sectionTitleIcon" aria-hidden="true">&#9742;</span>
          Phone Numbers
        </h4>
        <button
          type="button"
          class="profile__action-button u-profile-action-text"
          aria-label="Add another phone number"
          @click=${createNewRow}
        >
          <span class="profile__add-more-content">
            <span class="profile__add-more-icon" aria-hidden="true">${addIcon}</span>
            Add More
          </span>
        </button>
      </header>
      <fieldset>
        <legend class="sr-only">Phone number entries</legend>
        ${visiblePhones.map(({ index }, displayIndex) => renderContactPhoneInputRow({
          phones,
          index,
          displayIndex,
          onDelete: () => {
            deleteRow(phones, index)
            onAddRow()
          }
        }))}
      </fieldset>
    </section>
  `
}

function renderContactEmailInputRow({
  emails,
  index,
  displayIndex,
  onDelete
}: ContactEmailInputRowProps) {
  const emailRow = emails[index]
  const label = `Email Address ${displayIndex + 1}`
  const typeLabel = `Email Type ${displayIndex + 1}`
  const inputName = `email-value-${index}`
  const typeInputName = `email-type-${index}`

  const handleValueInput = (e: Event) => {
    const target = e.target as HTMLInputElement
    const nextValue = sanitizeEmailValue(target.value)
    if (emails[index]) {
      applyRowFieldChange(emails[index], 'value', nextValue, rowHasContent)
    }
  }

  const handleTypeInput = (e: Event) => {
    const target = e.target as HTMLSelectElement
    const nextType = target.value
    if (emails[index]) {
      applyRowSelectChange(emails[index], 'type', nextType)
    }
  }

  const handleDelete = (event: Event) => {
    event.preventDefault()
    onDelete()
  }

  return html`
    <div class="profile-edit-dialog__row">
      <label aria-label=${label} class="label profile-edit-dialog__field">
        <input
          class="input"
          type="email"
          name=${inputName}
          .value=${emailRow?.value || ''}
          required
          data-contact-field="value"
          data-entry-node=${emailRow?.entryNode || ''}
          data-row-status=${emailRow?.status || 'n/a'}
          placeholder="Email Address"
          autocomplete="email"
          inputmode="email"
          @input=${handleValueInput}
        />
      </label>
      <label aria-label=${typeLabel} class="label profile-edit-dialog__field-type">
        <select name=${typeInputName} id="email-type-select-${inputName}" @change=${handleTypeInput} .value=${emailRow?.type || ''}>
          <option value="Personal">Personal</option>
          <option value="Office">Office</option>
          <option value="Other">Other</option>
        </select>
      </label>
      <div class="inputActions">
        <button
          type="button"
          class="deleteEntryButton"
          aria-label=${`Delete email address ${displayIndex + 1}`}
          title=${deleteEntryButtonTitleText}
          @click=${handleDelete}
        >
          <svg class="deleteEntryIcon" viewBox="0 0 24 24" aria-hidden="true" focusable="false">
            <path d="M9 3h6l1 2h4v2H4V5h4l1-2zm-1 6h2v9H8V9zm6 0h2v9h-2V9zM6 9h12l-1 12H7L6 9z" />
          </svg>
        </button>
      </div>
    </div>
  `
}

function renderContactInfoEmailSection(emails: ContactPointRow[], onAddRow: () => void) {
  const createNewRow = (event: Event) => {
    event.preventDefault()
    emails.push({ value: '', type: '', entryNode: '', status: 'new' })
    onAddRow()
  }

  const visibleEmails = emails
    .map((email, index) => ({ email, index }))
    .filter(({ email }) => email.status !== 'deleted')

  return html`
    <section 
      aria-labelledby="email-addresses-heading" 
      class="contactsEditSection section-bg">
      <header class="profile__section-header">
        <h4 id="email-addresses-heading">
          <span class="sectionTitleIcon" aria-hidden="true">&#9993;</span>
          Email Addresses
        </h4>
        <button
          type="button"
          class="profile__action-button u-profile-action-text"
          aria-label="Add another email address"
          @click=${createNewRow}
        >
          <span class="profile__add-more-content">
            <span class="profile__add-more-icon" aria-hidden="true">${addIcon}</span>
            Add More
          </span>
        </button>
      </header>
      <fieldset>
        <legend class="sr-only">Email address entries</legend>
        ${visibleEmails.map(({ index }, displayIndex) => renderContactEmailInputRow({
          emails,
          index,
          displayIndex,
          onDelete: () => {
            deleteRow(emails, index)
            onAddRow()
          }
        }))}
      </fieldset>
    </section>
  `
}

function renderContactAddressInputRow({
  addresses,
  index,
  displayIndex,
  onDelete
}: ContactAddressInputRowProps) {
  const addressRow = addresses[index]
  const label = `Address ${displayIndex + 1}`
  const typeLabel = `Address Type ${displayIndex + 1}`
  const streetAddressName = `address-street-${index}`
  const localityName = `address-locality-${index}`
  const regionName = `address-region-${index}`
  const postalCodeName = `address-postal-${index}`
  const countryName = `address-country-${index}`
  const typeInputName = `address-type-${index}`
  const addressTypeSelectId = `address-type-select-${index}`

  const handleAddressInput = (field: ContactAddressEditableField) => (e: Event) => {
    const target = e.target as HTMLInputElement
    const nextValue = sanitizeAddressFieldValue(target.value)
    if (addresses[index]) {
      applyRowFieldChange(addresses[index], field, nextValue, rowHasContent)
    }
  }

  const handleTypeInput = (e: Event) => {
    const target = e.target as HTMLSelectElement
    const nextType = target.value
    if (addresses[index]) {
      applyRowSelectChange(addresses[index], 'type', nextType)
    }
  }

  const handleDelete = (event: Event) => {
    event.preventDefault()
    onDelete()
  }

  return html`
    <div class="profile-edit-dialog__row profile-edit-dialog__row--addressHeader">
      <label aria-label=${typeLabel} class="label profile-edit-dialog__field-type profile-edit-dialog__field-type--wide">
        Address Type
        <select name=${typeInputName} id=${addressTypeSelectId} @change=${handleTypeInput} .value=${addressRow?.type || ''}>
          <option value="Home">Home</option>
          <option value="Work">Work</option>
          <option value="Other">Other</option>
        </select>
      </label>
      <div class="inputActions inputActions--edge">
        <button
          type="button"
          class="deleteEntryButton"
          aria-label=${`Delete address ${displayIndex + 1}`}
          title=${deleteEntryButtonTitleText}
          @click=${handleDelete}
        >
          <svg class="deleteEntryIcon" viewBox="0 0 24 24" aria-hidden="true" focusable="false">
            <path d="M9 3h6l1 2h4v2H4V5h4l1-2zm-1 6h2v9H8V9zm6 0h2v9h-2V9zM6 9h12l-1 12H7L6 9z" />
          </svg>
        </button>
      </div>
    </div>
    <label aria-label=${`${label} Street`} class="label profile-edit-dialog__field">
      Street Address
      <input
        class="input"
        type="text"
        name=${streetAddressName}
        .value=${addressRow?.streetAddress || ''}
        required
        data-contact-field="streetAddress"
        data-entry-node=${addressRow?.entryNode || ''}
        data-row-status=${addressRow?.status || 'n/a'}
        placeholder="Street Address"
        autocomplete="street-address"
        inputmode="text"
        @change=${handleAddressInput('streetAddress')}
      />
    </label>

    <div class="profile-edit-dialog__row">
      <label aria-label=${`${label} Locality`} class="label profile-edit-dialog__field">
        Locality
        <input
          class="input"
          type="text"
          name=${localityName}
          .value=${addressRow?.locality || ''}
          data-contact-field="locality"
          data-entry-node=${addressRow?.entryNode || ''}
          data-row-status=${addressRow?.status || 'n/a'}
          placeholder="City / Locality"
          autocomplete="address-level2"
          inputmode="text"
          @change=${handleAddressInput('locality')}
        />
      </label>
      <label aria-label=${`${label} Postal Code`} class="label profile-edit-dialog__field">
        Postal Code
        <input
          class="input"
          type="text"
          name=${postalCodeName}
          .value=${addressRow?.postalCode || ''}
          data-contact-field="postalCode"
          data-entry-node=${addressRow?.entryNode || ''}
          data-row-status=${addressRow?.status || 'n/a'}
          placeholder="Postal Code"
          autocomplete="postal-code"
          inputmode="text"
          @change=${handleAddressInput('postalCode')}
        />
      </label>
    </div>

    <div class="profile-edit-dialog__row">
      <label aria-label=${`${label} Region`} class="label profile-edit-dialog__field">
        Region
        <input
          class="input"
          type="text"
          name=${regionName}
          .value=${addressRow?.region || ''}
          data-contact-field="region"
          data-entry-node=${addressRow?.entryNode || ''}
          data-row-status=${addressRow?.status || 'n/a'}
          placeholder="State / Region"
          autocomplete="address-level1"
          inputmode="text"
          @change=${handleAddressInput('region')}
        />
      </label>
      <label aria-label=${`${label} Country`} class="label profile-edit-dialog__field">
        Country
        <input
          class="input"
          type="text"
          name=${countryName}
          .value=${addressRow?.countryName || ''}
          data-contact-field="countryName"
          data-entry-node=${addressRow?.entryNode || ''}
          data-row-status=${addressRow?.status || 'n/a'}
          placeholder="Country"
          autocomplete="country-name"
          inputmode="text"
          @change=${handleAddressInput('countryName')}
        />
      </label>
    </div>
  `
}

function renderContactInfoAddressSection(addresses: ContactAddressRow[], onAddRow: () => void) {
  const createNewRow = (event: Event) => {
    event.preventDefault()
    addresses.push({
      streetAddress: '',
      locality: '',
      region: '',
      postalCode: '',
      countryName: '',
      type: '',
      entryNode: '',
      status: 'new'
    })
    onAddRow()
  }

  const visibleAddresses = addresses
    .map((address, index) => ({ address, index }))
    .filter(({ address }) => address.status !== 'deleted')

  return html`
    <section 
      aria-labelledby="address-heading" 
      class="contactsEditSection section-bg">
      <header class="profile__section-header">
        <h4 id="address-heading">
          <span class="sectionTitleIcon" aria-hidden="true">&#9993;</span>
          Addresses
        </h4>
        <button
          type="button"
          class="profile__action-button u-profile-action-text"
          aria-label="Add another address"
          @click=${createNewRow}
        >
          <span class="profile__add-more-content">
            <span class="profile__add-more-icon" aria-hidden="true">${addIcon}</span>
            Add More
          </span>
        </button>
      </header>
      <fieldset>
        <legend class="sr-only">Address entries</legend>
        ${visibleAddresses.map(({ index }, displayIndex) => renderContactAddressInputRow({
          addresses,
          index,
          displayIndex,
          onDelete: () => {
            deleteRow(addresses, index)
            onAddRow()
          }
        }))}
      </fieldset>
    </section>
  `
}

function renderContactInfoEditTemplate(form: HTMLFormElement, formState: ContactInfoFormState) {
  const rerender = () => renderContactInfoEditTemplate(form, formState)


  render(html`
    ${renderContactInfoPhoneSection(formState.phones, rerender)}
    ${renderContactInfoEmailSection(formState.emails, rerender)}
    ${renderContactInfoAddressSection(formState.addresses, rerender)}
  `, form)
}

function createContactInfoEditForm(contactInfo: ContactInfo) {
  const form = document.createElement('form')
  form.classList.add('profile__edit-form')

  const formState = toFormState(contactInfo)
  renderContactInfoEditTemplate(form, formState)

  return { form, formState }
}

function validateContactInfoBeforeSave(formState: ContactInfoFormState): string | null {
  const phoneOps = summarizeRowOps(formState.phones, rowHasContent)
  const emailOps = summarizeRowOps(formState.emails, rowHasContent)
  const addressOps = summarizeRowOps(formState.addresses, rowHasContent)
  const hasChanges =
    phoneOps.create.length > 0 || phoneOps.update.length > 0 || phoneOps.remove.length > 0 ||
    emailOps.create.length > 0 || emailOps.update.length > 0 || emailOps.remove.length > 0 ||
    addressOps.create.length > 0 || addressOps.update.length > 0 || addressOps.remove.length > 0

  if (!hasChanges) return 'No contact info changes detected.'
  return null
}


export async function createContactInfoEditDialog(
  event: Event,
  store: LiveStore,
  subject: NamedNode,
  contactInfo: ContactInfo,
  viewerMode: ViewerMode,
  onSaved?: () => Promise<void> | void
) {
  const dom = (event.currentTarget as HTMLElement | null)?.ownerDocument || document
  const { form, formState } = createContactInfoEditForm(contactInfo)

  const result = await openInputDialog({
    title: editContactInfoDialogTitleText,
    dom,
    form,
    headerAction: { type: 'close' },
    submitLabel: dialogSubmitLabelText,
    cancelLabel: dialogCancelLabelText,
    validate: () => {
      if (viewerMode !== 'owner') {
        return ownerLoginRequiredDialogMessageText
      }
      return validateContactInfoBeforeSave(formState)
    },
    onSave: async () => {
      const plan: ContactMutationPlan = {
        phoneOps: summarizeRowOps(formState.phones, rowHasContent),
        emailOps: summarizeRowOps(formState.emails, rowHasContent),
        addressOps: summarizeRowOps(formState.addresses, rowHasContent)
      }
      await processContactInfoMutations(store, subject, plan)
    },
    formatSaveError: (error: unknown) => {
      const message = error instanceof Error ? error.message : String(error)
      return `${saveContactUpdatesFailedPrefixText} ${message}`
    }
  })

  if (!result) return

  if (onSaved) {
    await onSaved()
  }
}
