import { openInputDialog } from '../../ui/dialog'
import { html, render } from 'lit-html'
import 'solid-ui/components/select'
import { ContactAddressRow, ContactInfo, ContactMutationPlan, ContactPointRow } from './types'
import '../../styles/EditDialogs.css'
import '../../styles/ContactInfoEditDialog.css'
import { LiveStore, NamedNode } from 'rdflib'
import { processContactInfoMutations } from './mutations'
import { ViewerMode } from '../../types'
import {
  combinePhoneValue,
  splitPhoneValue
} from '../shared/phoneCountries'
import { normalizeEmailTypeForContactInfoEdit, normalizePhoneTypeForContactInfoEdit } from '../shared/contactTypeUtils'
import { applyRowFieldChange, applyRowSelectChange, deleteRow, summarizeRowOps } from '../shared/rowState'
import { hasNonEmptyText, sanitizeTextValue, toText } from '../../textUtils'
import {
  deleteEntryButtonTitleText,
  dialogCancelLabelText,
  dialogSubmitLabelText,
  editContactInfoDialogTitleText,
  ownerLoginRequiredDialogMessageText,
  saveContactUpdatesFailedPrefixText
} from '../../texts'
import { sanitizeAddressFieldValue, sanitizeEmailValue, sanitizePhoneLocalValue } from '../shared/sanitizeUtils'
import { addIcon, locationIcon, trashIcon } from '../../icons-svg/profileIcons'
import { emailIcon, phoneIcon } from '../../icons-svg/contactIcons'

/* Some of the code in this file was generated by AI Model: GPT-5.3-Codex  */
/* Prompt: 1. are you able to create a little trash can icon at the end of 
              each entry so for each phone, email and address line.
           2. are you able to add all the country flags and prefix next to 
              the phone numbers? 
           3. can you write functions to sanitize the input values for emails, phones, and addresses? */

type ContactInfoFormState = {
  emails: ContactPointRow[]
  phones: ContactPointRow[]
  addresses: ContactAddressRow[]
}

type ContactInfoRerenderOptions = {
  focusSelector?: string
}

type ContactTypeSelectOption = {
  label: string
  value: string
}

type ContactTypeSelectKind = 'phone' | 'email'

type ContactTypeSelectElement = HTMLElement & {
  options?: ContactTypeSelectOption[]
  value?: string
  label?: string
}

const PHONE_TYPE_OPTIONS: ContactTypeSelectOption[] = [
  { label: 'Mobile', value: 'Cell' },
  { label: 'Home', value: 'Home' },
  { label: 'Work', value: 'Work' }
]

const EMAIL_TYPE_OPTIONS: ContactTypeSelectOption[] = [
  { label: 'Personal', value: 'Home' },
  { label: 'Office', value: 'Office' }
]

function normalizeContactTypeValue(value: string, options: ContactTypeSelectOption[]): string {
  return options.some((option) => option.value === value) ? value : options[0]?.value || ''
}

function readContactTypeChange(event: Event): string {
  const customEvent = event as CustomEvent<{ value?: string }>
  if (typeof customEvent.detail?.value === 'string') {
    return customEvent.detail.value
  }

  const target = event.target as HTMLSelectElement | HTMLInputElement | null
  return typeof target?.value === 'string' ? target.value : ''
}

function getContactTypeOptions(kind: ContactTypeSelectKind): ContactTypeSelectOption[] {
  return kind === 'phone' ? PHONE_TYPE_OPTIONS : EMAIL_TYPE_OPTIONS
}

function getContactTypeValue(
  kind: ContactTypeSelectKind,
  formState: ContactInfoFormState,
  rowIndex: number
): string {
  const row = kind === 'phone' ? formState.phones[rowIndex] : formState.emails[rowIndex]
  return normalizeContactTypeValue(row?.type || '', getContactTypeOptions(kind))
}

function initializeContactTypeSelects(form: HTMLFormElement, formState: ContactInfoFormState): void {
  const selectElements = form.querySelectorAll('solid-ui-select[data-contact-type-kind]') as NodeListOf<ContactTypeSelectElement>

  selectElements.forEach((selectElement) => {
    const kind = selectElement.dataset.contactTypeKind as ContactTypeSelectKind | undefined
    const rowIndex = Number(selectElement.dataset.rowIndex)
    if (!kind || Number.isNaN(rowIndex)) return

    selectElement.options = getContactTypeOptions(kind)
    selectElement.value = getContactTypeValue(kind, formState, rowIndex)
    selectElement.label = ''
  })
}

function isContactPointRow(row: ContactPointRow | ContactAddressRow): row is ContactPointRow {
  return 'value' in row
}

function rowHasContent(row: ContactPointRow | ContactAddressRow): boolean {
  if (isContactPointRow(row)) {
    return hasNonEmptyText(row.value)
  }

  return [
    row.streetAddress,
    row.locality,
    row.region,
    row.postalCode,
    row.countryName
  ].some(hasNonEmptyText)
}

function toFormState(contactInfo: ContactInfo): ContactInfoFormState {
  const emails = (contactInfo.emails || [])
    .map((email) => ({
      value: sanitizeEmailValue(toText(email.valueNode).replace(/^mailto:/i, '')),
      type: normalizeContactTypeValue(normalizeEmailTypeForContactInfoEdit(email.type), EMAIL_TYPE_OPTIONS),
      entryNode: toText(email.entryNode),
      status: toText(email.entryNode) ? 'existing' as const : 'new' as const
    }))
    .filter((email) => Boolean(email.value || email.entryNode || email.type))

  const phones = (contactInfo.phones || [])
    .map((phone) => ({
      value: sanitizeTextValue(toText(phone.valueNode).replace(/^tel:/i, '')),
      type: normalizeContactTypeValue(normalizePhoneTypeForContactInfoEdit(phone.type), PHONE_TYPE_OPTIONS),
      entryNode: toText(phone.entryNode),
      status: 'existing' as const
    }))
    .filter((phone) => Boolean(phone.value))
  const addresses = (contactInfo.addresses || [])
    .map((address) => ({
      streetAddress: sanitizeAddressFieldValue(toText(address.streetAddress)),
      locality: sanitizeAddressFieldValue(toText(address.locality)),
      region: sanitizeAddressFieldValue(toText(address.region)),
      postalCode: sanitizeAddressFieldValue(toText(address.postalCode)),
      countryName: sanitizeAddressFieldValue(toText(address.countryName)),
      type: toText(address.type),
      entryNode: toText(address.entryNode),
      status: toText(address.entryNode) ? 'existing' as const : 'new' as const
    }))
    .filter((address) => rowHasContent(address) || Boolean(address.entryNode || address.type))

  return {
    emails: emails.length ? emails : [{ value: '', type: EMAIL_TYPE_OPTIONS[0].value, entryNode: '', status: 'new' }],
    phones: phones.length ? phones : [{ value: '', type: PHONE_TYPE_OPTIONS[0].value, entryNode: '', status: 'new' }],
    addresses: addresses.length
      ? addresses
      : [{ streetAddress: '', locality: '', region: '', postalCode: '', countryName: '', type: '', entryNode: '', status: 'new' }]
  }
}

type ContactAddressEditableField =
  | 'streetAddress'
  | 'locality'
  | 'region'
  | 'postalCode'
  | 'countryName'

type ContactPhoneInputRowProps = {
  phones: ContactPointRow[]
  index: number
  displayIndex: number
  onDelete: () => void
}

type ContactEmailInputRowProps = {
  emails: ContactPointRow[]
  index: number
  displayIndex: number
  onDelete: () => void
}

type ContactAddressInputRowProps = {
  addresses: ContactAddressRow[]
  index: number
  displayIndex: number
  onDelete: () => void
}
/* not needed for now
function renderCountryPrefixSelect(
  name: string,
  value: string,
  label: string,
  onChange: (event: Event) => void
) {
  return html`
    <label class="label profile-edit-dialog__phone-prefix-field" aria-label=${label}>
      <select class="phonePrefixSelect" name=${name} .value=${value} @change=${onChange}>
        ${COUNTRY_PREFIX_OPTIONS.map((option) => html`
          <option value=${option.dialCode}>
            ${countryCodeToFlag(option.iso2)} ${option.dialCode}
          </option>
        `)}
      </select>
    </label>
  `
} */

function renderContactPhoneInputRow({
  phones,
  index,
  displayIndex,
  onDelete
}: ContactPhoneInputRowProps) {
  const phoneRow = phones[index]
  const label = `Phone Number ${displayIndex + 1}`
  // const countryCodeLabel = `Country Calling Code ${displayIndex + 1}`
  const typeLabel = `Phone Type ${displayIndex + 1}`
  // const prefixInputName = `phone-prefix-${index}`
  const inputName = `phone-value-${index}`
  const splitValue = splitPhoneValue(phoneRow?.value || '')
  let selectedDialCode = splitValue.dialCode

  const handleValueInput = (e: Event) => {
    const target = e.target as HTMLInputElement
    const nextValue = sanitizePhoneLocalValue(target.value)
    if (phones[index]) {
      applyRowFieldChange(phones[index], 'value', combinePhoneValue(selectedDialCode, nextValue), rowHasContent)
    }
  }
/* Not needed for now
  const handleCountryCodeInput = (e: Event) => {
    const target = e.target as HTMLSelectElement
    selectedDialCode = target.value

    if (phones[index]) {
      const localNumber = splitPhoneValue(phones[index].value).localNumber
      applyRowFieldChange(phones[index], 'value', combinePhoneValue(selectedDialCode, localNumber), rowHasContent)
    }
  } */

  const handleTypeInput = (e: Event) => {
    const nextType = readContactTypeChange(e)
    if (phones[index]) {
      applyRowSelectChange(phones[index], 'type', nextType)
    }
  }

  const handleDelete = (event: Event) => {
    event.preventDefault()
    onDelete()
  }

  return html`
    <div class="profile-edit-dialog__row profile-edit-dialog__row--contact-point">
      <div class="profile-edit-dialog__field">
        <label aria-label=${label} class="label">
          <input
            class="input"
            type="tel"
            name=${inputName}
            .value=${splitValue.localNumber}
            required
            data-contact-field="value"
            data-entry-node=${phoneRow?.entryNode || ''}
            data-row-status=${phoneRow?.status || 'n/a'}
            placeholder="Phone Number"
            autocomplete="tel-national"
            inputmode="tel"
            @input=${handleValueInput}
          />
        </label>
      </div>
      <label aria-label=${typeLabel} class="label profile-edit-dialog__field-type profile-edit-dialog__phone-type-row">
        <solid-ui-select
          class="profile-edit-dialog__type-select"
          id=${`phone-type-select-${inputName}`}
          data-contact-type-kind="phone"
          data-row-index=${String(index)}
          aria-label=${typeLabel}
          .label=${''}
          .options=${PHONE_TYPE_OPTIONS}
          .value=${normalizeContactTypeValue(phoneRow?.type || '', PHONE_TYPE_OPTIONS)}
          @change=${handleTypeInput}
        ></solid-ui-select>
      </label>
      <div class="profile-edit-dialog__actions">
        <button
          type="button"
          class="profile-edit-dialog__delete-button"
          aria-label=${`Delete phone number ${displayIndex + 1}`}
          title=${deleteEntryButtonTitleText}
          @click=${handleDelete}
        >
          <span class="profile-edit-dialog__delete-icon" aria-hidden="true">${trashIcon}</span>
        </button>
      </div>
    </div>
  `
}

function renderContactInfoPhoneSection(phones: ContactPointRow[], onAddRow: (options?: ContactInfoRerenderOptions) => void) {
  const createNewRow = (event: Event) => {
    event.preventDefault()
    phones.unshift({ value: '', type: PHONE_TYPE_OPTIONS[0].value, entryNode: '', status: 'new' })
    onAddRow({ focusSelector: '[name="phone-value-0"]' })
  }

  const visiblePhones = phones
    .map((phone, index) => ({ phone, index }))
    .filter(({ phone }) => phone.status !== 'deleted')

  return html`
    <section 
      aria-labelledby="phone-numbers-heading" 
      class="profile-edit-dialog__section">
      <header class="profile__section-header">
        <h3 id="phone-numbers-heading" class="profile-edit-dialog__section-heading">
          <span class="profile-edit-dialog__section-title-icon" aria-hidden="true">${phoneIcon}</span>
          Phone Numbers
        </h3>
        <button
          type="button"
          class="profile__action-button profile-action-text flex-center"
          aria-label="Add another phone number"
          @click=${createNewRow}
        >
          <span class="profile__add-more-content">
            <span class="profile__add-more-inline">
              <span class="profile__add-more-icon" aria-hidden="true">${addIcon}</span>
              <span>Add More</span>
            </span>
          </span>
        </button>
      </header>
      <fieldset>
        <legend class="sr-only">Phone number entries</legend>
        ${visiblePhones.map(({ index }, displayIndex) => renderContactPhoneInputRow({
          phones,
          index,
          displayIndex,
          onDelete: () => {
            deleteRow(phones, index)
            onAddRow()
          }
        }))}
      </fieldset>
    </section>
  `
}

function renderContactEmailInputRow({
  emails,
  index,
  displayIndex,
  onDelete
}: ContactEmailInputRowProps) {
  const emailRow = emails[index]
  const label = `Email Address ${displayIndex + 1}`
  const typeLabel = `Email Type ${displayIndex + 1}`
  const inputName = `email-value-${index}`

  const handleValueInput = (e: Event) => {
    const target = e.target as HTMLInputElement
    const nextValue = sanitizeEmailValue(target.value)
    if (emails[index]) {
      applyRowFieldChange(emails[index], 'value', nextValue, rowHasContent)
    }
  }

  const handleTypeInput = (e: Event) => {
    const nextType = readContactTypeChange(e)
    if (emails[index]) {
      applyRowSelectChange(emails[index], 'type', nextType)
    }
  }

  const handleDelete = (event: Event) => {
    event.preventDefault()
    onDelete()
  }

  return html`
    <div class="profile-edit-dialog__row profile-edit-dialog__row--contact-point">
      <label aria-label=${label} class="label profile-edit-dialog__field">
        <input
          class="input"
          type="email"
          name=${inputName}
          .value=${emailRow?.value || ''}
          required
          data-contact-field="value"
          data-entry-node=${emailRow?.entryNode || ''}
          data-row-status=${emailRow?.status || 'n/a'}
          placeholder="Email Address"
          autocomplete="email"
          inputmode="email"
          @input=${handleValueInput}
        />
      </label>
      <label aria-label=${typeLabel} class="label profile-edit-dialog__field-type emailTypeRow">
        <solid-ui-select
          class="profile-edit-dialog__type-select"
          id=${`email-type-select-${inputName}`}
          data-contact-type-kind="email"
          data-row-index=${String(index)}
          aria-label=${typeLabel}
          .label=${''}
          .options=${EMAIL_TYPE_OPTIONS}
          .value=${normalizeContactTypeValue(emailRow?.type || '', EMAIL_TYPE_OPTIONS)}
          @change=${handleTypeInput}
        ></solid-ui-select>
      </label>
      <div class="profile-edit-dialog__actions">
        <button
          type="button"
          class="profile-edit-dialog__delete-button"
          aria-label=${`Delete email address ${displayIndex + 1}`}
          title=${deleteEntryButtonTitleText}
          @click=${handleDelete}
        >
          <span class="profile-edit-dialog__delete-icon" aria-hidden="true">${trashIcon}</span>
        </button>
      </div>
    </div>
  `
}

function renderContactInfoEmailSection(emails: ContactPointRow[], onAddRow: (options?: ContactInfoRerenderOptions) => void) {
  const createNewRow = (event: Event) => {
    event.preventDefault()
    emails.unshift({ value: '', type: EMAIL_TYPE_OPTIONS[0].value, entryNode: '', status: 'new' })
    onAddRow({ focusSelector: '[name="email-value-0"]' })
  }

  const visibleEmails = emails
    .map((email, index) => ({ email, index }))
    .filter(({ email }) => email.status !== 'deleted')

  return html`
    <section 
      aria-labelledby="email-addresses-heading" 
      class="profile-edit-dialog__section">
      <header class="profile__section-header">
        <h3 id="email-addresses-heading" class="profile-edit-dialog__section-heading">
          <span class="profile-edit-dialog__section-title-icon" aria-hidden="true">${emailIcon}</span>
          Email Addresses
        </h3>
        <button
          type="button"
          class="profile__action-button profile-action-text flex-center"
          aria-label="Add another email address"
          @click=${createNewRow}
        >
          <span class="profile__add-more-content">
            <span class="profile__add-more-inline">
              <span class="profile__add-more-icon" aria-hidden="true">${addIcon}</span>
              <span>Add More</span>
            </span>
          </span>
        </button>
      </header>
      <fieldset>
        <legend class="sr-only">Email address entries</legend>
        ${visibleEmails.map(({ index }, displayIndex) => renderContactEmailInputRow({
          emails,
          index,
          displayIndex,
          onDelete: () => {
            deleteRow(emails, index)
            onAddRow()
          }
        }))}
      </fieldset>
    </section>
  `
}

function renderContactAddressInputRow({
  addresses,
  index,
  displayIndex,
  onDelete
}: ContactAddressInputRowProps) {
  const addressRow = addresses[index]
  const label = `Address ${displayIndex + 1}`
  const typeLabel = `Address Type ${displayIndex + 1}`
  const streetAddressName = `address-street-${index}`
  const localityName = `address-locality-${index}`
  const regionName = `address-region-${index}`
  const postalCodeName = `address-postal-${index}`
  const countryName = `address-country-${index}`
  const typeInputName = `address-type-${index}`
  const addressTypeSelectId = `address-type-select-${index}`

  const handleAddressInput = (field: ContactAddressEditableField) => (e: Event) => {
    const target = e.target as HTMLInputElement
    const nextValue = sanitizeAddressFieldValue(target.value)
    if (addresses[index]) {
      applyRowFieldChange(addresses[index], field, nextValue, rowHasContent)
    }
  }

  const handleTypeInput = (e: Event) => {
    const target = e.target as HTMLSelectElement
    const nextType = target.value
    if (addresses[index]) {
      applyRowSelectChange(addresses[index], 'type', nextType)
    }
  }

  const handleDelete = (event: Event) => {
    event.preventDefault()
    onDelete()
  }

  return html`
    <div class="profile-edit-dialog__row profile-edit-dialog__row--address-header profile-edit-dialog__row--full">
      <p class="profile-edit-dialog__address-title">${label}</p>
      <label aria-label=${typeLabel} class="label profile-edit-dialog__field-type profile-edit-dialog__field-type--wide hidden">
        Address Type
        <select name=${typeInputName} id=${addressTypeSelectId} @change=${handleTypeInput} .value=${addressRow?.type || ''}>
          <option value="Home">Home</option>
          <option value="Work">Work</option>
        </select>
      </label>
      <div class="profile-edit-dialog__actions profile-edit-dialog__actions--edge">
        <button
          type="button"
          class="profile-edit-dialog__delete-button"
          aria-label=${`Delete address ${displayIndex + 1}`}
          title=${deleteEntryButtonTitleText}
          @click=${handleDelete}
        >
          <span class="profile-edit-dialog__delete-icon" aria-hidden="true">${trashIcon}</span>
        </button>
      </div>
    </div>
    <div class="profile-edit-dialog__row profile-edit-dialog__row--full">
      <label aria-label=${`${label} Street`} class="label profile-edit-dialog__field profile-edit-dialog__field--full">
        Street Address
        <input
          class="input"
          type="text"
          name=${streetAddressName}
          .value=${addressRow?.streetAddress || ''}
          required
          data-contact-field="streetAddress"
          data-entry-node=${addressRow?.entryNode || ''}
          data-row-status=${addressRow?.status || 'n/a'}
          placeholder="Street Address"
          autocomplete="street-address"
          inputmode="text"
          @change=${handleAddressInput('streetAddress')}
        />
      </label>
    </div>
    <div class="profile-edit-dialog__row profile-edit-dialog__row--full profile-edit-dialog__row--equal">
      <label aria-label=${`${label} Locality`} class="label profile-edit-dialog__field">
        Locality
        <input
          class="input"
          type="text"
          name=${localityName}
          .value=${addressRow?.locality || ''}
          data-contact-field="locality"
          data-entry-node=${addressRow?.entryNode || ''}
          data-row-status=${addressRow?.status || 'n/a'}
          placeholder="City / Locality"
          autocomplete="address-level2"
          inputmode="text"
          @change=${handleAddressInput('locality')}
        />
      </label>
      <label aria-label=${`${label} Postal Code`} class="label profile-edit-dialog__field">
        Postal Code
        <input
          class="input"
          type="text"
          name=${postalCodeName}
          .value=${addressRow?.postalCode || ''}
          data-contact-field="postalCode"
          data-entry-node=${addressRow?.entryNode || ''}
          data-row-status=${addressRow?.status || 'n/a'}
          placeholder="Postal Code"
          autocomplete="postal-code"
          inputmode="text"
          @change=${handleAddressInput('postalCode')}
        />
      </label>
    </div>

    <div class="profile-edit-dialog__row profile-edit-dialog__row--full profile-edit-dialog__row--equal">
      <label aria-label=${`${label} Region`} class="label profile-edit-dialog__field">
        Region
        <input
          class="input"
          type="text"
          name=${regionName}
          .value=${addressRow?.region || ''}
          data-contact-field="region"
          data-entry-node=${addressRow?.entryNode || ''}
          data-row-status=${addressRow?.status || 'n/a'}
          placeholder="State / Region"
          autocomplete="address-level1"
          inputmode="text"
          @change=${handleAddressInput('region')}
        />
      </label>
      <label aria-label=${`${label} Country`} class="label profile-edit-dialog__field">
        Country
        <input
          class="input"
          type="text"
          name=${countryName}
          .value=${addressRow?.countryName || ''}
          data-contact-field="countryName"
          data-entry-node=${addressRow?.entryNode || ''}
          data-row-status=${addressRow?.status || 'n/a'}
          placeholder="Country"
          autocomplete="country-name"
          inputmode="text"
          @change=${handleAddressInput('countryName')}
        />
      </label>
    </div>
  `
}

function renderContactInfoAddressSection(addresses: ContactAddressRow[], onAddRow: (options?: ContactInfoRerenderOptions) => void) {
  const createNewRow = (event: Event) => {
    event.preventDefault()
    addresses.unshift({
      streetAddress: '',
      locality: '',
      region: '',
      postalCode: '',
      countryName: '',
      type: '',
      entryNode: '',
      status: 'new'
    })
    onAddRow({ focusSelector: '[name="address-street-0"]' })
  }

  const visibleAddresses = addresses
    .map((address, index) => ({ address, index }))
    .filter(({ address }) => address.status !== 'deleted')

  return html`
    <section 
      aria-labelledby="address-heading" 
      class="profile-edit-dialog__section">
      <header class="profile__section-header">
        <h3 id="address-heading" class="profile-edit-dialog__section-heading">
          <span class="profile-edit-dialog__section-title-icon" aria-hidden="true">${locationIcon}</span>
          Addresses
        </h3>
        <button
          type="button"
          class="profile__action-button profile-action-text flex-center"
          aria-label="Add another address"
          @click=${createNewRow}
        >
          <span class="profile__add-more-content">
            <span class="profile__add-more-inline">
              <span class="profile__add-more-icon" aria-hidden="true">${addIcon}</span>
              <span>Add More</span>
            </span>
          </span>
        </button>
      </header>
      <fieldset>
        <legend class="sr-only">Address entries</legend>
        ${visibleAddresses.map(({ index }, displayIndex) => renderContactAddressInputRow({
          addresses,
          index,
          displayIndex,
          onDelete: () => {
            deleteRow(addresses, index)
            onAddRow()
          }
        }))}
      </fieldset>
    </section>
  `
}

function focusContactInfoField(form: HTMLFormElement, selector: string): void {
  const nextField = form.querySelector(selector) as HTMLElement | null
  if (!nextField || typeof nextField.focus !== 'function') return

  nextField.scrollIntoView({ block: 'nearest', behavior: 'auto' })
  nextField.focus()
  if (nextField instanceof HTMLInputElement || nextField instanceof HTMLTextAreaElement) {
    nextField.select()
  }
}

function renderContactInfoEditTemplate(
  form: HTMLFormElement,
  formState: ContactInfoFormState,
  viewerMode: ViewerMode,
  options: ContactInfoRerenderOptions = {}
) {
  const rerender = (nextOptions: ContactInfoRerenderOptions = {}) => renderContactInfoEditTemplate(form, formState, viewerMode, nextOptions)


  render(html`
    ${renderContactInfoPhoneSection(formState.phones, rerender)}
    ${renderContactInfoEmailSection(formState.emails, rerender)}
    ${renderContactInfoAddressSection(formState.addresses, rerender)}
    ${viewerMode !== 'owner'
      ? html`<p class="profile-edit-dialog__login-message">${ownerLoginRequiredDialogMessageText}</p>`
      : null}
  `, form)

  initializeContactTypeSelects(form, formState)

  if (options.focusSelector) {
    focusContactInfoField(form, options.focusSelector)
  }
}

function createContactInfoEditForm(contactInfo: ContactInfo, viewerMode: ViewerMode) {
  const form = document.createElement('form')
  form.classList.add('profile__edit-form')
  form.classList.add('profile__edit-form--contact-info')

  const formState = toFormState(contactInfo)
  renderContactInfoEditTemplate(form, formState, viewerMode)

  return { form, formState }
}

function validateContactInfoBeforeSave(formState: ContactInfoFormState): string | null {
  const phoneOps = summarizeRowOps(formState.phones, rowHasContent)
  const emailOps = summarizeRowOps(formState.emails, rowHasContent)
  const addressOps = summarizeRowOps(formState.addresses, rowHasContent)
  const hasChanges =
    phoneOps.create.length > 0 || phoneOps.update.length > 0 || phoneOps.remove.length > 0 ||
    emailOps.create.length > 0 || emailOps.update.length > 0 || emailOps.remove.length > 0 ||
    addressOps.create.length > 0 || addressOps.update.length > 0 || addressOps.remove.length > 0

  if (!hasChanges) return 'No contact info changes detected.'
  return null
}


export async function createContactInfoEditDialog(
  event: Event,
  store: LiveStore,
  subject: NamedNode,
  contactInfo: ContactInfo,
  viewerMode: ViewerMode,
  onSaved?: () => Promise<void> | void
) {
  const dom = (event.currentTarget as HTMLElement | null)?.ownerDocument || document
  const { form, formState } = createContactInfoEditForm(contactInfo, viewerMode)

  const result = await openInputDialog({
    title: editContactInfoDialogTitleText,
    dom,
    form,
    headerAction: { type: 'close' },
    submitLabel: dialogSubmitLabelText,
    cancelLabel: dialogCancelLabelText,
    validate: () => {
      if (viewerMode !== 'owner') {
        return ownerLoginRequiredDialogMessageText
      }
      return validateContactInfoBeforeSave(formState)
    },
    onSave: async () => {
      const plan: ContactMutationPlan = {
        phoneOps: summarizeRowOps(formState.phones, rowHasContent),
        emailOps: summarizeRowOps(formState.emails, rowHasContent),
        addressOps: summarizeRowOps(formState.addresses, rowHasContent)
      }
      await processContactInfoMutations(store, subject, plan)
    },
    formatSaveError: (error: unknown) => {
      const message = error instanceof Error ? error.message : String(error)
      return `${saveContactUpdatesFailedPrefixText} ${message}`
    }
  })

  if (!result) return

  if (onSaved) {
    await onSaved()
  }
}
