import { LiveStore, NamedNode, Node, st } from 'rdflib'
import { fallbackSaveUpdatesErrorMessageText, updaterUnsupportedStoreErrorMessageText } from '../../texts'
import { PrefixCapable, RdfStatement } from './types'
/* The following helper was generated by AI Model: GPT-5.4.
   Prompt: can you add types to rdfMutationHelpers.ts and consolidate mutation logic 
   where appropriate. */
function normalizeNodeId(value: string): string {
  return value.startsWith('_:') ? value.slice(2) : value
}

function isCompleteStatement(statement: RdfStatement | null | undefined): statement is RdfStatement {
  return Boolean(statement?.subject && statement?.predicate && statement?.object)
}

function statementTermKey(term: { toNT?: () => string; value?: string } | null | undefined): string {
  if (!term) return ''
  if (typeof term.toNT === 'function') return term.toNT()
  return term.value || ''
}

export function registerStorePrefix(target: PrefixCapable | undefined, prefix: string, uri: string): void {
  if (!target) return
  if (typeof target.setPrefixForURI === 'function') {
    target.setPrefixForURI(prefix, uri)
    return
  }
  if (!target.namespaces) {
    target.namespaces = {}
  }
  target.namespaces[prefix] = uri
}

export function statementKey(statement: RdfStatement): string {
  return `${statementTermKey(statement.subject)} ${statementTermKey(statement.predicate)} ${statementTermKey(statement.object)} ${statementTermKey(statement.why)}`
}

export function uniqueStatements(statements: RdfStatement[]): RdfStatement[] {
  return Array.from(new Map((statements || []).map((statement) => [statementKey(statement), statement])).values())
}

export function applyStatementsToStore(store: LiveStore, deletions: RdfStatement[], insertions: RdfStatement[]): void {
  store.remove(deletions)
  insertions.forEach((statement) => {
    store.add(statement.subject, statement.predicate, statement.object, statement.why)
  })
}

export function sanitizePatchStatements(
  store: LiveStore,
  deletions: RdfStatement[],
  insertions: RdfStatement[],
  requireStoredDelete = false
) {
  const safeDeletions = uniqueStatements(
    (deletions || []).filter((statement) => {
      if (!isCompleteStatement(statement)) return false
      if (store.holds(statement.subject, statement.predicate, statement.object, statement.why)) return true
      return requireStoredDelete
        ? false
        : store.statementsMatching(statement.subject, statement.predicate, statement.object, statement.why).length > 0
    })
  )

  const safeInsertions = uniqueStatements((insertions || []).filter(isCompleteStatement))

  return { safeDeletions, safeInsertions }
}

export function applyUpdaterPatch(store: LiveStore, deletions: RdfStatement[], insertions: RdfStatement[]) {
  if (!store.updater) {
    throw new Error(updaterUnsupportedStoreErrorMessageText)
  }

  const { safeDeletions, safeInsertions } = sanitizePatchStatements(store, deletions, insertions, true)

  const updater = store.updater as unknown as { update?: (deletions: RdfStatement[], insertions: RdfStatement[], callback: (_uri: string, ok: boolean, message?: string) => void) => void }

  if (safeDeletions.length === 0 && safeInsertions.length === 0) {
    return Promise.resolve()
  }

  return new Promise<void>((resolve, reject) => {
    try {
      updater.update?.(
        safeDeletions,
        safeInsertions,
        (_uri: string, ok: boolean, message?: string) => {
          if (ok === true) {
            resolve()
            return
          }
          reject(new Error(message || fallbackSaveUpdatesErrorMessageText))
        }
      )
    } catch (error) {
      reject(error instanceof Error ? error : new Error(String(error)))
    }
  })
}

export function collectNodeStatements(store: LiveStore, node: Node, doc: NamedNode) {
  return store.statementsMatching(node as any, null, null, doc)
}

export function collectLinkStatements(
  store: LiveStore,
  subject: NamedNode,
  predicate: NamedNode,
  node: Node,
  doc: NamedNode
) {
  return store.statementsMatching(subject, predicate, node, doc)
}

/* The following helper was generated by AI Model: GPT-5.3-Codex.
   Prompt: 'do you see anything I can do differently in the mutation code so that it's not so verbose and possible reusable accross sections' */
export function replacePredicateStatements(
  store: LiveStore,
  subject: NamedNode,
  predicate: NamedNode,
  doc: NamedNode,
  deletions: RdfStatement[],
  insertions: RdfStatement[],
  nextObject?: Node | null
) {
  deletions.push(...store.statementsMatching(subject, predicate, null, doc))
  if (nextObject) {
    insertions.push(st(subject, predicate, nextObject, doc))
  }
}

/* The following helper was generated by AI Model: GPT-5.3-Codex.
   Prompt: 'do you see anything I can do differently in the mutation code so that it's not so verbose and possible reusable accross sections' */
export function collectLinkedNodeStatements(
  store: LiveStore,
  sourceNode: Node,
  predicate: NamedNode,
  doc: NamedNode
) {
  const linkedNodes = store.each(sourceNode as any, predicate, null, doc) as Node[]
  const linkedStatements = linkedNodes.flatMap((linkedNode) => collectNodeStatements(store, linkedNode, doc))
  const linkStatements = store.statementsMatching(sourceNode as any, predicate, null, doc)

  return {
    linkedNodes,
    linkedStatements,
    linkStatements
  }
}

export function findExistingNode(nodes: Node[], entryNode: string) {
  const normalizedEntryNode = normalizeNodeId(entryNode)
  return nodes.find((node) => {
    const nodeValue = normalizeNodeId(node.value)
    if (nodeValue === normalizedEntryNode) return true
    return node.value === entryNode
  })
}
