import { LiveStore, NamedNode, Node, st } from 'rdflib'
import { fallbackSaveUpdatesErrorMessageText, updaterUnsupportedStoreErrorMessageText } from '../../texts'
import { PrefixCapable, RdfFetcher, RdfStatement, RdfUpdater } from './types'
/* Some of the code below was generated by AI Model: GPT-5.4.
   Prompt: can you add types to rdfMutationHelpers.ts and consolidate mutation logic 
   where appropriate. */
function normalizeNodeId(value: string): string {
  return value.startsWith('_:') ? value.slice(2) : value
}

function isCompleteStatement(statement: RdfStatement | null | undefined): statement is RdfStatement {
  return Boolean(statement?.subject && statement?.predicate && statement?.object)
}

function statementTermKey(term: { toNT?: () => string; value?: string } | null | undefined): string {
  if (!term) return ''
  if (typeof term.toNT === 'function') return term.toNT()
  return term.value || ''
}

export function registerStorePrefix(target: PrefixCapable | undefined, prefix: string, uri: string): void {
  if (!target) return
  if (typeof target.setPrefixForURI === 'function') {
    target.setPrefixForURI(prefix, uri)
    return
  }
  if (!target.namespaces) {
    target.namespaces = {}
  }
  target.namespaces[prefix] = uri
}

export function statementKey(statement: RdfStatement): string {
  return `${statementTermKey(statement.subject)} ${statementTermKey(statement.predicate)} ${statementTermKey(statement.object)} ${statementTermKey(statement.why)}`
}

export function uniqueStatements(statements: RdfStatement[]): RdfStatement[] {
  return Array.from(new Map((statements || []).map((statement) => [statementKey(statement), statement])).values())
}

export function applyStatementsToStore(store: LiveStore, deletions: RdfStatement[], insertions: RdfStatement[]): void {
  store.remove(deletions)
  insertions.forEach((statement) => {
    store.add(statement.subject, statement.predicate, statement.object, statement.why)
  })
}

export function sanitizePatchStatements(
  store: LiveStore,
  deletions: RdfStatement[],
  insertions: RdfStatement[],
  requireStoredDelete = false
) {
  const safeDeletions = uniqueStatements(
    (deletions || []).filter((statement) => {
      if (!isCompleteStatement(statement)) return false
      if (store.holds(statement.subject, statement.predicate, statement.object, statement.why)) return true
      return requireStoredDelete
        ? false
        : store.statementsMatching(statement.subject, statement.predicate, statement.object, statement.why).length > 0
    })
  )

  const safeInsertions = uniqueStatements((insertions || []).filter(isCompleteStatement))

  return { safeDeletions, safeInsertions }
}

function getStoreUpdater(store: LiveStore): RdfUpdater | undefined {
  return store.updater as RdfUpdater | undefined
}

function getStoreFetcher(store: LiveStore): RdfFetcher | undefined {
  return store.fetcher as RdfFetcher | undefined
}

export function isPatchFailureMessage(message: string): boolean {
  const text = (message || '').toLowerCase()
  return (
    text.includes('fetch error for patch') ||
    text.includes('failed to fetch') ||
    text.includes(' on patch ') ||
    text.includes('web error: 400') ||
    text.includes('web error: 405') ||
    text.includes('web error: 500') ||
    text.includes('web error: 501')
  )
}

export function isMissingGetRecordErrorMessage(message: string): boolean {
  return (message || '').toLowerCase().includes('no record of our http get request for document')
}

function runUpdaterUpdate(
  updater: RdfUpdater,
  deletions: RdfStatement[],
  insertions: RdfStatement[],
  failureMessage: string
) {
  if (typeof updater.update !== 'function') {
    throw new Error(updaterUnsupportedStoreErrorMessageText)
  }

  return new Promise<void>((resolve, reject) => {
    try {
      updater.update(deletions, insertions, (_uri: string, ok: boolean, message?: string) => {
        if (ok === true) {
          resolve()
          return
        }
        reject(new Error(message || failureMessage))
      })
    } catch (error) {
      reject(error instanceof Error ? error : new Error(String(error)))
    }
  })
}

export async function putResourceWithStatements(
  store: LiveStore,
  doc: NamedNode,
  deletions: RdfStatement[],
  insertions: RdfStatement[],
  unsupportedMessage: string
) {
  const updater = getStoreUpdater(store)
  const fetcher = getStoreFetcher(store)

  if (!updater || typeof updater.serialize !== 'function' || !fetcher || typeof fetcher.webOperation !== 'function') {
    throw new Error(unsupportedMessage)
  }

  const currentStatements = store.statementsMatching(undefined, undefined, undefined, doc).slice()
  const deletionKeys = new Set((deletions || []).map((statement) => statementKey(statement)))
  const nextStatements = currentStatements.filter((statement) => !deletionKeys.has(statementKey(statement))).concat(insertions || [])

  const contentType = 'text/turtle'
  const body = updater.serialize(doc.value, nextStatements, contentType)
  const response = await fetcher.webOperation('PUT', doc.value, {
    noMeta: true,
    contentType,
    body
  })

  if (!response || response.ok !== true) {
    const status = response?.status || 'unknown'
    throw new Error(`Web error: ${status} on PUT of <${doc.value}>`)
  }

  applyStatementsToStore(store, deletions, insertions)
}

type UpdateTransportOptions = {
  unsupportedMessage: string
  failureMessage?: string
  requireStoredDelete?: boolean
  useDavFallback?: boolean
  usePutFallback?: boolean
  patchFailureMatcher?: (message: string) => boolean
  missingGetRecordMatcher?: (message: string) => boolean
}

export async function runUpdateTransport(
  store: LiveStore,
  doc: NamedNode | null,
  deletions: RdfStatement[],
  insertions: RdfStatement[],
  options: UpdateTransportOptions
) {
  const updater = getStoreUpdater(store)
  if (!updater) {
    throw new Error(options.unsupportedMessage)
  }

  const {
    safeDeletions,
    safeInsertions
  } = sanitizePatchStatements(store, deletions, insertions, options.requireStoredDelete === true)

  if (safeDeletions.length === 0 && safeInsertions.length === 0) {
    return
  }

  const failureMessage = options.failureMessage || fallbackSaveUpdatesErrorMessageText
  const isPatchFailure = options.patchFailureMatcher || isPatchFailureMessage
  const isMissingGetRecord = options.missingGetRecordMatcher || isMissingGetRecordErrorMessage

  try {
    await runUpdaterUpdate(updater, safeDeletions, safeInsertions, failureMessage)
    return
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error)
    if (!isPatchFailure(message)) {
      throw error
    }

    if (options.useDavFallback && typeof updater.updateDav === 'function') {
      if (doc && getStoreFetcher(store)?.load) {
        try {
          await getStoreFetcher(store)?.load?.(doc)
        } catch {
          // Continue to DAV fallback and then PUT fallback if needed.
        }
      }

      try {
        await new Promise<void>((resolve, reject) => {
          updater.updateDav?.(doc, safeDeletions, safeInsertions, (_uri: string, ok: boolean, body?: string) => {
            if (ok === true) {
              resolve()
              return
            }
            reject(new Error(body || message || failureMessage))
          })
        })
        return
      } catch (davError) {
        const davMessage = davError instanceof Error ? davError.message : String(davError)
        if (!options.usePutFallback || !isMissingGetRecord(davMessage)) {
          throw davError
        }
      }
    }

    if (options.usePutFallback) {
      if (!doc) {
        throw new Error(options.unsupportedMessage)
      }
      await putResourceWithStatements(store, doc, safeDeletions, safeInsertions, options.unsupportedMessage)
      return
    }

    throw error
  }
}

export function applyUpdaterPatch(store: LiveStore, deletions: RdfStatement[], insertions: RdfStatement[]) {
  if (!store.updater) {
    throw new Error(updaterUnsupportedStoreErrorMessageText)
  }

  return runUpdateTransport(store, null, deletions, insertions, {
    unsupportedMessage: updaterUnsupportedStoreErrorMessageText,
    failureMessage: fallbackSaveUpdatesErrorMessageText,
    requireStoredDelete: true,
    useDavFallback: false,
    usePutFallback: false
  })
}

export function collectNodeStatements(store: LiveStore, node: Node, doc: NamedNode) {
  return store.statementsMatching(node as any, null, null, doc)
}

export function collectLinkStatements(
  store: LiveStore,
  subject: NamedNode,
  predicate: NamedNode,
  node: Node,
  doc: NamedNode
) {
  return store.statementsMatching(subject, predicate, node, doc)
}

/* The following helper was generated by AI Model: GPT-5.3-Codex.
   Prompt: 'do you see anything I can do differently in the mutation code so that it's not so verbose and possible reusable accross sections' */
export function replacePredicateStatements(
  store: LiveStore,
  subject: NamedNode,
  predicate: NamedNode,
  doc: NamedNode,
  deletions: RdfStatement[],
  insertions: RdfStatement[],
  nextObject?: Node | null
) {
  deletions.push(...store.statementsMatching(subject, predicate, null, doc))
  if (nextObject) {
    insertions.push(st(subject, predicate, nextObject, doc))
  }
}

/* The following helper was generated by AI Model: GPT-5.3-Codex.
   Prompt: 'do you see anything I can do differently in the mutation code so that it's not so verbose and possible reusable accross sections' */
export function collectLinkedNodeStatements(
  store: LiveStore,
  sourceNode: Node,
  predicate: NamedNode,
  doc: NamedNode
) {
  const linkedNodes = store.each(sourceNode as any, predicate, null, doc) as Node[]
  const linkedStatements = linkedNodes.flatMap((linkedNode) => collectNodeStatements(store, linkedNode, doc))
  const linkStatements = store.statementsMatching(sourceNode as any, predicate, null, doc)

  return {
    linkedNodes,
    linkedStatements,
    linkStatements
  }
}

export function findExistingNode(nodes: Node[], entryNode: string) {
  const normalizedEntryNode = normalizeNodeId(entryNode)
  return nodes.find((node) => {
    const nodeValue = normalizeNodeId(node.value)
    if (nodeValue === normalizedEntryNode) return true
    return node.value === entryNode
  })
}
