type DateLike = string | { value?: string } | null | undefined

let descriptionResizeBound = false

function toDateValue(date?: DateLike): string {
  if (!date) return ''
  if (typeof date === 'string') return date
  return date.value || ''
}

/* Function below generated by AI Model: GPT-5.3-Codex */
/* Prompt: the description needs to only show 2 lines and then more button
   please generate code for this. */
export function updateDescriptionOverflow(root: ParentNode = document) {
  const selectorGroups = [
    {
      wrap: '.resume-card__description-wrap',
      text: '.resume-card__description-text',
      toggle: '.resume-card__description-toggle',
      expanded: 'resume-card__description-text--expanded'
    },
    {
      wrap: '.education-card__description-wrap',
      text: '.education-card__description-text',
      toggle: '.education-card__description-toggle',
      expanded: 'education-card__description-text--expanded'
    },
    {
      wrap: '.bio-card__description-wrap',
      text: '.bio-card__description-text',
      toggle: '.bio-card__description-toggle',
      expanded: 'bio-card__description-text--expanded'
    }
  ]

  selectorGroups.forEach(({ wrap, text, toggle, expanded }) => {
    const wraps = root.querySelectorAll(wrap)
    wraps.forEach((container) => {
      const textEl = container.querySelector(text) as HTMLElement | null
      const button = container.querySelector(toggle) as HTMLButtonElement | null
      if (!textEl || !button) return

      const isExpanded = textEl.classList.contains(expanded)
      if (isExpanded) {
        button.hidden = false
        return
      }

      const isOverflowing = textEl.scrollHeight > textEl.clientHeight + 1
      button.hidden = !isOverflowing
      if (!isOverflowing) {
        button.setAttribute('aria-expanded', 'false')
        button.textContent = '...more'
      }
    })
  })
}

export function scheduleDescriptionOverflowCheck() {
  if (typeof window === 'undefined') return
  window.requestAnimationFrame(() => updateDescriptionOverflow(window.document))

  if (!descriptionResizeBound) {
    window.addEventListener('resize', () => scheduleDescriptionOverflowCheck())
    descriptionResizeBound = true
  }
}

export function toggleDescription(event: Event) {
  event.preventDefault()
  event.stopPropagation()
  ;(event as any).stopImmediatePropagation?.()

  const button = event.currentTarget as HTMLButtonElement | null
  if (!button) return

  const descriptionId = button.getAttribute('aria-controls')
  if (!descriptionId) return

  const textEl = document.getElementById(descriptionId)
  if (!textEl) return

  const expandedClass =
    textEl.matches('.resume-card__description-text')
      ? 'resume-card__description-text--expanded'
      : textEl.matches('.education-card__description-text')
        ? 'education-card__description-text--expanded'
        : textEl.matches('.bio-card__description-text')
          ? 'bio-card__description-text--expanded'
          : 'isExpanded'

  const isExpanded = textEl.classList.toggle(expandedClass)
  button.setAttribute('aria-expanded', isExpanded ? 'true' : 'false')
  button.textContent = isExpanded ? '...less' : '...more'
  if (!isExpanded) {
    scheduleDescriptionOverflowCheck()
  }
}

/* Function below generated by AI Model: GPT-5.3-Codex */
/* Prompt: write me a function to convert a date to Month, Year */
export function formatMonthYear(date?: DateLike): string {
  const value = toDateValue(date)
  if (!value) return ''

  const year = value.slice(0, 4)
  const month = value.slice(5, 7)
  const monthNames = [
    'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
    'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'
  ]
  const monthIndex = Number(month) - 1

  if (!year || monthIndex < 0 || monthIndex > 11) return value
  return `${monthNames[monthIndex]}, ${year}`
}

export function datesAsText(startDate?: DateLike, endDate?: DateLike): string {
  const startValue = toDateValue(startDate)
  if (!startValue) return ''

  const start = formatMonthYear(startDate)
  const end = toDateValue(endDate) ? formatMonthYear(endDate) : 'Present'
  return `${start} to ${end}`
}

export function toMonthDateTime(date?: DateLike): string | undefined {
  const value = toDateValue(date)
  if (!value) return undefined
  return value.slice(0, 7)
}
