import { html, TemplateResult } from 'lit-html'
import { LiveStore, NamedNode } from 'rdflib'
import { ns, utils } from 'solid-ui'
import './styles/QRCodeCard.css'
import { scanQrToConnectText } from './texts'
/* Part of this code was generated by AI Model: GPT-5.3-Codex */
/* Prompt: The QRCode has a label "link to profile" but it should
 be a VCARD with name, and link to profile. So when you scan it 
 it goes into your contacts. That's the current way works, IIRC. */
type LegacySubjectArg = NamedNode | string

function isNamedNodeLike(value: unknown): value is NamedNode {
  return Boolean(value && typeof value === 'object' && typeof (value as any).uri === 'string')
}

function isStoreLike(value: unknown): value is LiveStore {
  return Boolean(value && typeof value === 'object' && typeof (value as any).any === 'function')
}

function resolveQRCodeArgs(
  arg1: LegacySubjectArg,
  arg2?: unknown,
  arg3?: unknown
): { subject: NamedNode, store?: LiveStore } {
  if (isNamedNodeLike(arg1)) {
    return {
      subject: arg1,
      store: isStoreLike(arg2) ? arg2 : undefined
    }
  }

  if (isNamedNodeLike(arg3)) {
    return {
      subject: arg3,
      store: isStoreLike(arg2) ? arg2 : undefined
    }
  }

  throw new Error('QRCodeCard requires a profile subject NamedNode.')
}

function normalizeEmail(value: string): string {
  return (value || '').trim().replace(/^mailto:/i, '')
}

function normalizeTelephone(value: string): string {
  return (value || '').trim().replace(/^tel:/i, '')
}

function firstContactValue(
  store: LiveStore | undefined,
  subject: NamedNode,
  predicate: NamedNode,
  kind: 'email' | 'tel'
): string {
  if (!store) return ''

  const candidates = store.each(subject, predicate)
  for (const node of candidates) {
    if (!node) continue

    const direct = (node as any).value
    if (typeof direct === 'string' && direct.trim()) {
      return kind === 'email' ? normalizeEmail(direct) : normalizeTelephone(direct)
    }

    if (node.termType === 'NamedNode' || node.termType === 'BlankNode') {
      const viaValue = store.anyValue(node as any, ns.vcard('value'))
      if (typeof viaValue === 'string' && viaValue.trim()) {
        return kind === 'email' ? normalizeEmail(viaValue) : normalizeTelephone(viaValue)
      }
    }
  }

  return ''
}

export const QRCodeCard = (
  arg1: LegacySubjectArg,
  arg2?: unknown,
  arg3?: unknown
): TemplateResult => {
  const { subject, store } = resolveQRCodeArgs(arg1, arg2, arg3)
  const name = utils.label(subject)

  const escapeVCardValue = (value: string): string => {
    return (value || '')
      .replace(/\\/g, '\\\\')
      .replace(/;/g, '\\;')
      .replace(/,/g, '\\,')
      .replace(/\r?\n/g, '\\n')
  }

  const safeName = escapeVCardValue(name || subject.uri)
  const safeUrl = escapeVCardValue(subject.uri)
  const email = firstContactValue(store, subject, ns.vcard('hasEmail'), 'email')
  const telephone = firstContactValue(store, subject, ns.vcard('hasTelephone'), 'tel')
  const vCardLines = [
    'BEGIN:VCARD',
    'VERSION:4.0',
    `FN:${safeName}`,
    `URL:${safeUrl}`,
  ]

  if (email) {
    vCardLines.push(`EMAIL;TYPE=internet:${escapeVCardValue(email)}`)
  }

  if (telephone) {
    vCardLines.push(`TEL:${escapeVCardValue(telephone)}`)
  }

  vCardLines.push('END:VCARD')
  const vCard = vCardLines.join('\r\n')

  // console.log(`@@ qrcodes colours highlightColor ${highlightColor}, backgroundColor ${backgroundColor}`)
  
   
  return html`
    <figure 
      class="QRCode"
      data-value="${vCard}"
      data-testid="qrcode-card"
      aria-labelledby="qr-code-caption"
      role="img"
      aria-describedby="qr-code-description"
    >
      <div 
        aria-label="Static QR code containing contact information for ${name}"
        role="img"
        tabindex="0"
      ></div>
      <figcaption 
        id="qr-code-caption" 
        class="qrCaption"
      >
        ${scanQrToConnectText}
      </figcaption>
      <div 
        id="qr-code-description" 
        class="sr-only"
      >
        This is a static QR code containing vCard information for ${name}, including profile URL ${subject.uri}. The QR code is not interactive.
      </div>
    </figure>
  `
}
