// QR CODE
export const scanQrToConnectText = 'View Your Profile'
//ERRORS & SUCCESS
//Same 'not logged in' error message like on 'Chat with me' button
export const userNotLoggedInErrorMessage = 'Current user not found! Not logged in?'
export const internalErrorMessage = 'An internal error occured!'
export const friendWasAddedSuccesMessage = 'Friend was added!'

//OTHER
export const friendExistsMessage = 'Friend already exists'
export const loadingMessage = 'Loading...'

//BUTTONS
export const addMeToYourFriendsButtonText = 'Add as friend'
export const logInToChatWithMeButtonText = 'Login to chat with me'
export const friendExistsAlreadyButtonText = 'Already part of friends'
export const chatWithMeButtonText = 'Chat with me'

// Profile & Edit profile texts 
export const yourContactInformationHeading = 'Your profile'
export const otherPreferencesHeadingText = 'Other preferences'
export const communitiesHeadingText = 'Your communities'
export const resumeHeadingText = 'Resume'
export const bioHeadingText = 'Bio'
export const educationHeadingText = 'Education'
export const skillsHeadingText = 'Skills'
export const languagesHeadingText = 'Languages'
export const projectsHeadingText = 'Projects & Communities'
export const contactInfoHeadingText = 'More Contacts'
export const editSkillsDialogTitleText = 'Edit Skills'
export const editLanguagesDialogTitleText = 'Edit Languages'
export const editContactInfoDialogTitleText = 'Edit More Contacts'
export const editResumeDialogTitleText = 'Edit Resume'
export const editEducationDialogTitleText = 'Edit Education'
export const editProjectsDialogTitleText = 'Edit Projects & Communities'
export const editHeadingDialogTitleText = 'Edit Heading'
export const editSocialDialogTitleText = 'Edit Social Accounts'
export const editBioDialogTitleText = 'Edit Bio'
export const dialogSubmitLabelText = 'Save Changes'
export const dialogCancelLabelText = 'Cancel'
export const deleteEntryButtonTitleText = 'Delete entry'
export const ownerLoginRequiredDialogMessageText = 'You need to log in as the profile owner to save contact updates.'
export const loginRequiredDialogTitleText = 'Login Required'
export const saveFailedDialogTitleText = 'Save Failed'
export const saveContactUpdatesFailedPrefixText = 'Could not save contact updates.'
export const saveHeadingUpdatesFailedPrefixText = 'Could not save heading updates.'
export const saveLanguageUpdatesFailedPrefixText = 'Could not save language updates.'
export const saveResumeUpdatesFailedPrefixText = 'Could not save resume updates.'
export const saveEducationUpdatesFailedPrefixText = 'Could not save education updates.'
export const saveProjectsUpdatesFailedPrefixText = 'Could not save projects updates.'
export const saveSocialUpdatesFailedPrefixText = 'Could not save social accounts updates.'
export const saveBioUpdatesFailedPrefixText = 'Could not save bio updates.'
export const mutationSaveContactInfoFailedPrefixText = 'Failed to save contact info:'
export const mutationSaveLanguagesFailedPrefixText = 'Failed to save languages:'
export const mutationSaveSkillsFailedPrefixText = 'Failed to save skills:'
export const mutationSaveResumeFailedPrefixText = 'Failed to save resume:'
export const mutationEducationFailedPrefixText = 'Failed to save education:'
export const mutationBioFailedPrefixText = 'Failed to save bio:'
export const resumeUpdateEntryNotFoundErrorMessageText = 'Could not find existing resume entry for update. Please reload profile data and try again.'
export const bioUpdateEntryNotFoundErrorMessageText = 'Could not find existing bio entry for update. Please reload profile data and try again.'
export const updaterUnsupportedStoreErrorMessageText = 'Store does not support updates'
export const fallbackSaveUpdatesErrorMessageText = 'Failed to save updates'
export const socialAccountsHeadingText = 'Follow me on'
export const sharedItemsHeadingText = 'Shared items'
export const friendsHeadingText = 'Friends'
export const contactHeadingText = 'Contact'